//
// Copyright 2023 Signal Messenger, LLC
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: org/signal/chat/calling.proto

package calling

import (
	_ "go.mau.fi/mautrix-signal/pkg/signalmeow/protobuf/rpc/require"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCallingRelaysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallingRelaysRequest) Reset() {
	*x = GetCallingRelaysRequest{}
	mi := &file_org_signal_chat_calling_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallingRelaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallingRelaysRequest) ProtoMessage() {}

func (x *GetCallingRelaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_calling_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallingRelaysRequest.ProtoReflect.Descriptor instead.
func (*GetCallingRelaysRequest) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_calling_proto_rawDescGZIP(), []int{0}
}

type GetCallingRelaysResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A collection of calling relays a client may use for one-on-one calls.
	Relays        []*GetCallingRelaysResponse_Relay `protobuf:"bytes,1,rep,name=relays,proto3" json:"relays,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallingRelaysResponse) Reset() {
	*x = GetCallingRelaysResponse{}
	mi := &file_org_signal_chat_calling_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallingRelaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallingRelaysResponse) ProtoMessage() {}

func (x *GetCallingRelaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_calling_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallingRelaysResponse.ProtoReflect.Descriptor instead.
func (*GetCallingRelaysResponse) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_calling_proto_rawDescGZIP(), []int{1}
}

func (x *GetCallingRelaysResponse) GetRelays() []*GetCallingRelaysResponse_Relay {
	if x != nil {
		return x.Relays
	}
	return nil
}

type GetCallingRelaysResponse_HostnameUrlList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A collection of hostname-based TURN, TURNS, or STUN URLs a client can use
	// to connect to a relay.
	Urls          []string `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallingRelaysResponse_HostnameUrlList) Reset() {
	*x = GetCallingRelaysResponse_HostnameUrlList{}
	mi := &file_org_signal_chat_calling_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallingRelaysResponse_HostnameUrlList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallingRelaysResponse_HostnameUrlList) ProtoMessage() {}

func (x *GetCallingRelaysResponse_HostnameUrlList) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_calling_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallingRelaysResponse_HostnameUrlList.ProtoReflect.Descriptor instead.
func (*GetCallingRelaysResponse_HostnameUrlList) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_calling_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetCallingRelaysResponse_HostnameUrlList) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type GetCallingRelaysResponse_IpUrlList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A collection of IP-based TURN, TURNS, or STUN URLs a client can use to
	// connect to a relay.
	Urls []string `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	// A hostname clients must use to validate the relay's TLS certificate when
	// connecting via an IP-based TURNS URL. May not be specified if `urls`
	// contains no TURNS URLs.
	Hostname      *string `protobuf:"bytes,2,opt,name=hostname,proto3,oneof" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallingRelaysResponse_IpUrlList) Reset() {
	*x = GetCallingRelaysResponse_IpUrlList{}
	mi := &file_org_signal_chat_calling_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallingRelaysResponse_IpUrlList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallingRelaysResponse_IpUrlList) ProtoMessage() {}

func (x *GetCallingRelaysResponse_IpUrlList) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_calling_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallingRelaysResponse_IpUrlList.ProtoReflect.Descriptor instead.
func (*GetCallingRelaysResponse_IpUrlList) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_calling_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetCallingRelaysResponse_IpUrlList) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *GetCallingRelaysResponse_IpUrlList) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

type GetCallingRelaysResponse_Relay struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A username that can be presented to authenticate with a TURN server.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// A password that can be presented to authenticate with a TURN server.
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// The duration, in seconds, after which the included username and password
	// will no longer be valid.
	CredentialTtlSeconds uint64 `protobuf:"varint,3,opt,name=credential_ttl_seconds,json=credentialTtlSeconds,proto3" json:"credential_ttl_seconds,omitempty"`
	// A collection of hostname-based URLs clients may use to connect to this
	// relay.
	HostnameUrls *GetCallingRelaysResponse_HostnameUrlList `protobuf:"bytes,4,opt,name=hostname_urls,json=hostnameUrls,proto3,oneof" json:"hostname_urls,omitempty"`
	// A collection of IP-based URLs clients may use to connect to this relay.
	IpUrls        *GetCallingRelaysResponse_IpUrlList `protobuf:"bytes,5,opt,name=ip_urls,json=ipUrls,proto3,oneof" json:"ip_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallingRelaysResponse_Relay) Reset() {
	*x = GetCallingRelaysResponse_Relay{}
	mi := &file_org_signal_chat_calling_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallingRelaysResponse_Relay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallingRelaysResponse_Relay) ProtoMessage() {}

func (x *GetCallingRelaysResponse_Relay) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_calling_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallingRelaysResponse_Relay.ProtoReflect.Descriptor instead.
func (*GetCallingRelaysResponse_Relay) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_calling_proto_rawDescGZIP(), []int{1, 2}
}

func (x *GetCallingRelaysResponse_Relay) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetCallingRelaysResponse_Relay) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GetCallingRelaysResponse_Relay) GetCredentialTtlSeconds() uint64 {
	if x != nil {
		return x.CredentialTtlSeconds
	}
	return 0
}

func (x *GetCallingRelaysResponse_Relay) GetHostnameUrls() *GetCallingRelaysResponse_HostnameUrlList {
	if x != nil {
		return x.HostnameUrls
	}
	return nil
}

func (x *GetCallingRelaysResponse_Relay) GetIpUrls() *GetCallingRelaysResponse_IpUrlList {
	if x != nil {
		return x.IpUrls
	}
	return nil
}

var File_org_signal_chat_calling_proto protoreflect.FileDescriptor

const file_org_signal_chat_calling_proto_rawDesc = "" +
	"\n" +
	"\x1dorg/signal/chat/calling.proto\x12\x17org.signal.chat.calling\x1a\x1dorg/signal/chat/require.proto\"\x19\n" +
	"\x17GetCallingRelaysRequest\"\xbf\x04\n" +
	"\x18GetCallingRelaysResponse\x12O\n" +
	"\x06relays\x18\x01 \x03(\v27.org.signal.chat.calling.GetCallingRelaysResponse.RelayR\x06relays\x1a%\n" +
	"\x0fHostnameUrlList\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urls\x1aM\n" +
	"\tIpUrlList\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urls\x12\x1f\n" +
	"\bhostname\x18\x02 \x01(\tH\x00R\bhostname\x88\x01\x01B\v\n" +
	"\t_hostname\x1a\xdb\x02\n" +
	"\x05Relay\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x124\n" +
	"\x16credential_ttl_seconds\x18\x03 \x01(\x04R\x14credentialTtlSeconds\x12k\n" +
	"\rhostname_urls\x18\x04 \x01(\v2A.org.signal.chat.calling.GetCallingRelaysResponse.HostnameUrlListH\x00R\fhostnameUrls\x88\x01\x01\x12Y\n" +
	"\aip_urls\x18\x05 \x01(\v2;.org.signal.chat.calling.GetCallingRelaysResponse.IpUrlListH\x01R\x06ipUrls\x88\x01\x01B\x10\n" +
	"\x0e_hostname_urlsB\n" +
	"\n" +
	"\b_ip_urls2\x8a\x01\n" +
	"\aCalling\x12y\n" +
	"\x10GetCallingRelays\x120.org.signal.chat.calling.GetCallingRelaysRequest\x1a1.org.signal.chat.calling.GetCallingRelaysResponse\"\x00\x1a\x04\xc8\xd5\"\x01B\x02P\x01b\x06proto3"

var (
	file_org_signal_chat_calling_proto_rawDescOnce sync.Once
	file_org_signal_chat_calling_proto_rawDescData []byte
)

func file_org_signal_chat_calling_proto_rawDescGZIP() []byte {
	file_org_signal_chat_calling_proto_rawDescOnce.Do(func() {
		file_org_signal_chat_calling_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_signal_chat_calling_proto_rawDesc), len(file_org_signal_chat_calling_proto_rawDesc)))
	})
	return file_org_signal_chat_calling_proto_rawDescData
}

var file_org_signal_chat_calling_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_org_signal_chat_calling_proto_goTypes = []any{
	(*GetCallingRelaysRequest)(nil),                  // 0: org.signal.chat.calling.GetCallingRelaysRequest
	(*GetCallingRelaysResponse)(nil),                 // 1: org.signal.chat.calling.GetCallingRelaysResponse
	(*GetCallingRelaysResponse_HostnameUrlList)(nil), // 2: org.signal.chat.calling.GetCallingRelaysResponse.HostnameUrlList
	(*GetCallingRelaysResponse_IpUrlList)(nil),       // 3: org.signal.chat.calling.GetCallingRelaysResponse.IpUrlList
	(*GetCallingRelaysResponse_Relay)(nil),           // 4: org.signal.chat.calling.GetCallingRelaysResponse.Relay
}
var file_org_signal_chat_calling_proto_depIdxs = []int32{
	4, // 0: org.signal.chat.calling.GetCallingRelaysResponse.relays:type_name -> org.signal.chat.calling.GetCallingRelaysResponse.Relay
	2, // 1: org.signal.chat.calling.GetCallingRelaysResponse.Relay.hostname_urls:type_name -> org.signal.chat.calling.GetCallingRelaysResponse.HostnameUrlList
	3, // 2: org.signal.chat.calling.GetCallingRelaysResponse.Relay.ip_urls:type_name -> org.signal.chat.calling.GetCallingRelaysResponse.IpUrlList
	0, // 3: org.signal.chat.calling.Calling.GetCallingRelays:input_type -> org.signal.chat.calling.GetCallingRelaysRequest
	1, // 4: org.signal.chat.calling.Calling.GetCallingRelays:output_type -> org.signal.chat.calling.GetCallingRelaysResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_org_signal_chat_calling_proto_init() }
func file_org_signal_chat_calling_proto_init() {
	if File_org_signal_chat_calling_proto != nil {
		return
	}
	file_org_signal_chat_calling_proto_msgTypes[3].OneofWrappers = []any{}
	file_org_signal_chat_calling_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_signal_chat_calling_proto_rawDesc), len(file_org_signal_chat_calling_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_org_signal_chat_calling_proto_goTypes,
		DependencyIndexes: file_org_signal_chat_calling_proto_depIdxs,
		MessageInfos:      file_org_signal_chat_calling_proto_msgTypes,
	}.Build()
	File_org_signal_chat_calling_proto = out.File
	file_org_signal_chat_calling_proto_goTypes = nil
	file_org_signal_chat_calling_proto_depIdxs = nil
}
