//
// Copyright 2023 Signal Messenger, LLC
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: org/signal/chat/device.proto

package device

import (
	common "go.mau.fi/mautrix-signal/pkg/signalmeow/protobuf/rpc/common"
	errors "go.mau.fi/mautrix-signal/pkg/signalmeow/protobuf/rpc/errors"
	_ "go.mau.fi/mautrix-signal/pkg/signalmeow/protobuf/rpc/require"
	_ "go.mau.fi/mautrix-signal/pkg/signalmeow/protobuf/rpc/tag"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDevicesRequest) Reset() {
	*x = GetDevicesRequest{}
	mi := &file_org_signal_chat_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesRequest) ProtoMessage() {}

func (x *GetDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesRequest.ProtoReflect.Descriptor instead.
func (*GetDevicesRequest) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_device_proto_rawDescGZIP(), []int{0}
}

type GetDevicesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of devices linked to the authenticated account.
	Devices       []*GetDevicesResponse_LinkedDevice `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDevicesResponse) Reset() {
	*x = GetDevicesResponse{}
	mi := &file_org_signal_chat_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesResponse) ProtoMessage() {}

func (x *GetDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesResponse.ProtoReflect.Descriptor instead.
func (*GetDevicesResponse) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_device_proto_rawDescGZIP(), []int{1}
}

func (x *GetDevicesResponse) GetDevices() []*GetDevicesResponse_LinkedDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

type RemoveDeviceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier for the device to remove from the authenticated account. The
	// identifier must not be for the primary device.
	Id            uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDeviceRequest) Reset() {
	*x = RemoveDeviceRequest{}
	mi := &file_org_signal_chat_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDeviceRequest) ProtoMessage() {}

func (x *RemoveDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDeviceRequest.ProtoReflect.Descriptor instead.
func (*RemoveDeviceRequest) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_device_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveDeviceRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SetDeviceNameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A sequence of bytes that encodes an encrypted human-readable name for this
	// device.
	Name []byte `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The identifier for the device for which to set a name.
	Id            uint32 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDeviceNameRequest) Reset() {
	*x = SetDeviceNameRequest{}
	mi := &file_org_signal_chat_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDeviceNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceNameRequest) ProtoMessage() {}

func (x *SetDeviceNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceNameRequest.ProtoReflect.Descriptor instead.
func (*SetDeviceNameRequest) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_device_proto_rawDescGZIP(), []int{3}
}

func (x *SetDeviceNameRequest) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *SetDeviceNameRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SetDeviceNameResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*SetDeviceNameResponse_Success
	//	*SetDeviceNameResponse_TargetDeviceNotFound
	Response      isSetDeviceNameResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDeviceNameResponse) Reset() {
	*x = SetDeviceNameResponse{}
	mi := &file_org_signal_chat_device_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDeviceNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceNameResponse) ProtoMessage() {}

func (x *SetDeviceNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_device_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceNameResponse.ProtoReflect.Descriptor instead.
func (*SetDeviceNameResponse) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_device_proto_rawDescGZIP(), []int{4}
}

func (x *SetDeviceNameResponse) GetResponse() isSetDeviceNameResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *SetDeviceNameResponse) GetSuccess() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Response.(*SetDeviceNameResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *SetDeviceNameResponse) GetTargetDeviceNotFound() *errors.NotFound {
	if x != nil {
		if x, ok := x.Response.(*SetDeviceNameResponse_TargetDeviceNotFound); ok {
			return x.TargetDeviceNotFound
		}
	}
	return nil
}

type isSetDeviceNameResponse_Response interface {
	isSetDeviceNameResponse_Response()
}

type SetDeviceNameResponse_Success struct {
	// The device name was successfully set
	Success *emptypb.Empty `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type SetDeviceNameResponse_TargetDeviceNotFound struct {
	// No device with the provided identifier was found on the account
	TargetDeviceNotFound *errors.NotFound `protobuf:"bytes,2,opt,name=target_device_not_found,json=targetDeviceNotFound,proto3,oneof"`
}

func (*SetDeviceNameResponse_Success) isSetDeviceNameResponse_Response() {}

func (*SetDeviceNameResponse_TargetDeviceNotFound) isSetDeviceNameResponse_Response() {}

type RemoveDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDeviceResponse) Reset() {
	*x = RemoveDeviceResponse{}
	mi := &file_org_signal_chat_device_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDeviceResponse) ProtoMessage() {}

func (x *RemoveDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_device_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDeviceResponse.ProtoReflect.Descriptor instead.
func (*RemoveDeviceResponse) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_device_proto_rawDescGZIP(), []int{5}
}

type SetPushTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to TokenRequest:
	//
	//	*SetPushTokenRequest_ApnsTokenRequest_
	//	*SetPushTokenRequest_FcmTokenRequest_
	TokenRequest  isSetPushTokenRequest_TokenRequest `protobuf_oneof:"token_request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPushTokenRequest) Reset() {
	*x = SetPushTokenRequest{}
	mi := &file_org_signal_chat_device_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPushTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPushTokenRequest) ProtoMessage() {}

func (x *SetPushTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_device_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPushTokenRequest.ProtoReflect.Descriptor instead.
func (*SetPushTokenRequest) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_device_proto_rawDescGZIP(), []int{6}
}

func (x *SetPushTokenRequest) GetTokenRequest() isSetPushTokenRequest_TokenRequest {
	if x != nil {
		return x.TokenRequest
	}
	return nil
}

func (x *SetPushTokenRequest) GetApnsTokenRequest() *SetPushTokenRequest_ApnsTokenRequest {
	if x != nil {
		if x, ok := x.TokenRequest.(*SetPushTokenRequest_ApnsTokenRequest_); ok {
			return x.ApnsTokenRequest
		}
	}
	return nil
}

func (x *SetPushTokenRequest) GetFcmTokenRequest() *SetPushTokenRequest_FcmTokenRequest {
	if x != nil {
		if x, ok := x.TokenRequest.(*SetPushTokenRequest_FcmTokenRequest_); ok {
			return x.FcmTokenRequest
		}
	}
	return nil
}

type isSetPushTokenRequest_TokenRequest interface {
	isSetPushTokenRequest_TokenRequest()
}

type SetPushTokenRequest_ApnsTokenRequest_ struct {
	// If present, specifies the APNs device token(s) the server will use to
	// send new message notifications to the authenticated device.
	ApnsTokenRequest *SetPushTokenRequest_ApnsTokenRequest `protobuf:"bytes,1,opt,name=apns_token_request,json=apnsTokenRequest,proto3,oneof"`
}

type SetPushTokenRequest_FcmTokenRequest_ struct {
	// If present, specifies the FCM push token the server will use to send new
	// message notifications to the authenticated device.
	FcmTokenRequest *SetPushTokenRequest_FcmTokenRequest `protobuf:"bytes,2,opt,name=fcm_token_request,json=fcmTokenRequest,proto3,oneof"`
}

func (*SetPushTokenRequest_ApnsTokenRequest_) isSetPushTokenRequest_TokenRequest() {}

func (*SetPushTokenRequest_FcmTokenRequest_) isSetPushTokenRequest_TokenRequest() {}

type SetPushTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPushTokenResponse) Reset() {
	*x = SetPushTokenResponse{}
	mi := &file_org_signal_chat_device_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPushTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPushTokenResponse) ProtoMessage() {}

func (x *SetPushTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_device_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPushTokenResponse.ProtoReflect.Descriptor instead.
func (*SetPushTokenResponse) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_device_proto_rawDescGZIP(), []int{7}
}

type ClearPushTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearPushTokenRequest) Reset() {
	*x = ClearPushTokenRequest{}
	mi := &file_org_signal_chat_device_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearPushTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearPushTokenRequest) ProtoMessage() {}

func (x *ClearPushTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_device_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearPushTokenRequest.ProtoReflect.Descriptor instead.
func (*ClearPushTokenRequest) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_device_proto_rawDescGZIP(), []int{8}
}

type ClearPushTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearPushTokenResponse) Reset() {
	*x = ClearPushTokenResponse{}
	mi := &file_org_signal_chat_device_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearPushTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearPushTokenResponse) ProtoMessage() {}

func (x *ClearPushTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_device_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearPushTokenResponse.ProtoReflect.Descriptor instead.
func (*ClearPushTokenResponse) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_device_proto_rawDescGZIP(), []int{9}
}

type SetCapabilitiesRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Capabilities  []common.DeviceCapability `protobuf:"varint,1,rep,packed,name=capabilities,proto3,enum=org.signal.chat.common.DeviceCapability" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCapabilitiesRequest) Reset() {
	*x = SetCapabilitiesRequest{}
	mi := &file_org_signal_chat_device_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCapabilitiesRequest) ProtoMessage() {}

func (x *SetCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_device_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*SetCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_device_proto_rawDescGZIP(), []int{10}
}

func (x *SetCapabilitiesRequest) GetCapabilities() []common.DeviceCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type SetCapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCapabilitiesResponse) Reset() {
	*x = SetCapabilitiesResponse{}
	mi := &file_org_signal_chat_device_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCapabilitiesResponse) ProtoMessage() {}

func (x *SetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_device_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*SetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_device_proto_rawDescGZIP(), []int{11}
}

type GetDevicesResponse_LinkedDevice struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier for the device within an account.
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// A sequence of bytes that encodes an encrypted human-readable name for
	// this device.
	Name []byte `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The approximate time, in milliseconds since the epoch, at which this
	// device last connected to the server.
	LastSeen uint64 `protobuf:"varint,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	// The registration ID of the given device.
	RegistrationId uint32 `protobuf:"varint,4,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	// A sequence of bytes that encodes the time,
	// in milliseconds since the epoch, at which this device was
	// attached to its parent account.
	CreatedAtCiphertext []byte `protobuf:"bytes,5,opt,name=created_at_ciphertext,json=createdAtCiphertext,proto3" json:"created_at_ciphertext,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetDevicesResponse_LinkedDevice) Reset() {
	*x = GetDevicesResponse_LinkedDevice{}
	mi := &file_org_signal_chat_device_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevicesResponse_LinkedDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesResponse_LinkedDevice) ProtoMessage() {}

func (x *GetDevicesResponse_LinkedDevice) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_device_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesResponse_LinkedDevice.ProtoReflect.Descriptor instead.
func (*GetDevicesResponse_LinkedDevice) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_device_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetDevicesResponse_LinkedDevice) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetDevicesResponse_LinkedDevice) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *GetDevicesResponse_LinkedDevice) GetLastSeen() uint64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *GetDevicesResponse_LinkedDevice) GetRegistrationId() uint32 {
	if x != nil {
		return x.RegistrationId
	}
	return 0
}

func (x *GetDevicesResponse_LinkedDevice) GetCreatedAtCiphertext() []byte {
	if x != nil {
		return x.CreatedAtCiphertext
	}
	return nil
}

type SetPushTokenRequest_ApnsTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A "standard" APNs device token.
	ApnsToken     string `protobuf:"bytes,1,opt,name=apns_token,json=apnsToken,proto3" json:"apns_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPushTokenRequest_ApnsTokenRequest) Reset() {
	*x = SetPushTokenRequest_ApnsTokenRequest{}
	mi := &file_org_signal_chat_device_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPushTokenRequest_ApnsTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPushTokenRequest_ApnsTokenRequest) ProtoMessage() {}

func (x *SetPushTokenRequest_ApnsTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_device_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPushTokenRequest_ApnsTokenRequest.ProtoReflect.Descriptor instead.
func (*SetPushTokenRequest_ApnsTokenRequest) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_device_proto_rawDescGZIP(), []int{6, 0}
}

func (x *SetPushTokenRequest_ApnsTokenRequest) GetApnsToken() string {
	if x != nil {
		return x.ApnsToken
	}
	return ""
}

type SetPushTokenRequest_FcmTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An FCM push token.
	FcmToken      string `protobuf:"bytes,1,opt,name=fcm_token,json=fcmToken,proto3" json:"fcm_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPushTokenRequest_FcmTokenRequest) Reset() {
	*x = SetPushTokenRequest_FcmTokenRequest{}
	mi := &file_org_signal_chat_device_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPushTokenRequest_FcmTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPushTokenRequest_FcmTokenRequest) ProtoMessage() {}

func (x *SetPushTokenRequest_FcmTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_device_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPushTokenRequest_FcmTokenRequest.ProtoReflect.Descriptor instead.
func (*SetPushTokenRequest_FcmTokenRequest) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_device_proto_rawDescGZIP(), []int{6, 1}
}

func (x *SetPushTokenRequest_FcmTokenRequest) GetFcmToken() string {
	if x != nil {
		return x.FcmToken
	}
	return ""
}

var File_org_signal_chat_device_proto protoreflect.FileDescriptor

const file_org_signal_chat_device_proto_rawDesc = "" +
	"\n" +
	"\x1corg/signal/chat/device.proto\x12\x16org.signal.chat.device\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1corg/signal/chat/common.proto\x1a\x1corg/signal/chat/errors.proto\x1a\x1dorg/signal/chat/require.proto\x1a\x19org/signal/chat/tag.proto\"\x13\n" +
	"\x11GetDevicesRequest\"\x9f\x02\n" +
	"\x12GetDevicesResponse\x12Q\n" +
	"\adevices\x18\x01 \x03(\v27.org.signal.chat.device.GetDevicesResponse.LinkedDeviceR\adevices\x1a\xb5\x01\n" +
	"\fLinkedDevice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\fR\x04name\x12\x1b\n" +
	"\tlast_seen\x18\x03 \x01(\x04R\blastSeen\x120\n" +
	"\x0fregistration_id\x18\x04 \x01(\rB\a\xb2\x97\"\x03\x10\xff\x7fR\x0eregistrationId\x122\n" +
	"\x15created_at_ciphertext\x18\x05 \x01(\fR\x13createdAtCiphertext\"%\n" +
	"\x13RemoveDeviceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"E\n" +
	"\x14SetDeviceNameRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\fB\t\x9a\x97\"\x05\b\x01\x10\xe1\x01R\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\rR\x02id\"\xc1\x01\n" +
	"\x15SetDeviceNameResponse\x122\n" +
	"\asuccess\x18\x01 \x01(\v2\x16.google.protobuf.EmptyH\x00R\asuccess\x12h\n" +
	"\x17target_device_not_found\x18\x02 \x01(\v2 .org.signal.chat.errors.NotFoundB\r\xc2\xd5\"\tnot_foundH\x00R\x14targetDeviceNotFoundB\n" +
	"\n" +
	"\bresponse\"\x16\n" +
	"\x14RemoveDeviceResponse\"\xee\x02\n" +
	"\x13SetPushTokenRequest\x12l\n" +
	"\x12apns_token_request\x18\x01 \x01(\v2<.org.signal.chat.device.SetPushTokenRequest.ApnsTokenRequestH\x00R\x10apnsTokenRequest\x12i\n" +
	"\x11fcm_token_request\x18\x02 \x01(\v2;.org.signal.chat.device.SetPushTokenRequest.FcmTokenRequestH\x00R\x0ffcmTokenRequest\x1a7\n" +
	"\x10ApnsTokenRequest\x12#\n" +
	"\n" +
	"apns_token\x18\x01 \x01(\tB\x04\x88\x97\"\x01R\tapnsToken\x1a4\n" +
	"\x0fFcmTokenRequest\x12!\n" +
	"\tfcm_token\x18\x01 \x01(\tB\x04\x88\x97\"\x01R\bfcmTokenB\x0f\n" +
	"\rtoken_request\"\x16\n" +
	"\x14SetPushTokenResponse\"\x17\n" +
	"\x15ClearPushTokenRequest\"\x18\n" +
	"\x16ClearPushTokenResponse\"f\n" +
	"\x16SetCapabilitiesRequest\x12L\n" +
	"\fcapabilities\x18\x01 \x03(\x0e2(.org.signal.chat.common.DeviceCapabilityR\fcapabilities\"\x19\n" +
	"\x17SetCapabilitiesResponse2\xa9\x05\n" +
	"\aDevices\x12e\n" +
	"\n" +
	"GetDevices\x12).org.signal.chat.device.GetDevicesRequest\x1a*.org.signal.chat.device.GetDevicesResponse\"\x00\x12k\n" +
	"\fRemoveDevice\x12+.org.signal.chat.device.RemoveDeviceRequest\x1a,.org.signal.chat.device.RemoveDeviceResponse\"\x00\x12n\n" +
	"\rSetDeviceName\x12,.org.signal.chat.device.SetDeviceNameRequest\x1a-.org.signal.chat.device.SetDeviceNameResponse\"\x00\x12k\n" +
	"\fSetPushToken\x12+.org.signal.chat.device.SetPushTokenRequest\x1a,.org.signal.chat.device.SetPushTokenResponse\"\x00\x12q\n" +
	"\x0eClearPushToken\x12-.org.signal.chat.device.ClearPushTokenRequest\x1a..org.signal.chat.device.ClearPushTokenResponse\"\x00\x12t\n" +
	"\x0fSetCapabilities\x12..org.signal.chat.device.SetCapabilitiesRequest\x1a/.org.signal.chat.device.SetCapabilitiesResponse\"\x00\x1a\x04\xc8\xd5\"\x01B\x02P\x01b\x06proto3"

var (
	file_org_signal_chat_device_proto_rawDescOnce sync.Once
	file_org_signal_chat_device_proto_rawDescData []byte
)

func file_org_signal_chat_device_proto_rawDescGZIP() []byte {
	file_org_signal_chat_device_proto_rawDescOnce.Do(func() {
		file_org_signal_chat_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_signal_chat_device_proto_rawDesc), len(file_org_signal_chat_device_proto_rawDesc)))
	})
	return file_org_signal_chat_device_proto_rawDescData
}

var file_org_signal_chat_device_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_org_signal_chat_device_proto_goTypes = []any{
	(*GetDevicesRequest)(nil),                    // 0: org.signal.chat.device.GetDevicesRequest
	(*GetDevicesResponse)(nil),                   // 1: org.signal.chat.device.GetDevicesResponse
	(*RemoveDeviceRequest)(nil),                  // 2: org.signal.chat.device.RemoveDeviceRequest
	(*SetDeviceNameRequest)(nil),                 // 3: org.signal.chat.device.SetDeviceNameRequest
	(*SetDeviceNameResponse)(nil),                // 4: org.signal.chat.device.SetDeviceNameResponse
	(*RemoveDeviceResponse)(nil),                 // 5: org.signal.chat.device.RemoveDeviceResponse
	(*SetPushTokenRequest)(nil),                  // 6: org.signal.chat.device.SetPushTokenRequest
	(*SetPushTokenResponse)(nil),                 // 7: org.signal.chat.device.SetPushTokenResponse
	(*ClearPushTokenRequest)(nil),                // 8: org.signal.chat.device.ClearPushTokenRequest
	(*ClearPushTokenResponse)(nil),               // 9: org.signal.chat.device.ClearPushTokenResponse
	(*SetCapabilitiesRequest)(nil),               // 10: org.signal.chat.device.SetCapabilitiesRequest
	(*SetCapabilitiesResponse)(nil),              // 11: org.signal.chat.device.SetCapabilitiesResponse
	(*GetDevicesResponse_LinkedDevice)(nil),      // 12: org.signal.chat.device.GetDevicesResponse.LinkedDevice
	(*SetPushTokenRequest_ApnsTokenRequest)(nil), // 13: org.signal.chat.device.SetPushTokenRequest.ApnsTokenRequest
	(*SetPushTokenRequest_FcmTokenRequest)(nil),  // 14: org.signal.chat.device.SetPushTokenRequest.FcmTokenRequest
	(*emptypb.Empty)(nil),                        // 15: google.protobuf.Empty
	(*errors.NotFound)(nil),                      // 16: org.signal.chat.errors.NotFound
	(common.DeviceCapability)(0),                 // 17: org.signal.chat.common.DeviceCapability
}
var file_org_signal_chat_device_proto_depIdxs = []int32{
	12, // 0: org.signal.chat.device.GetDevicesResponse.devices:type_name -> org.signal.chat.device.GetDevicesResponse.LinkedDevice
	15, // 1: org.signal.chat.device.SetDeviceNameResponse.success:type_name -> google.protobuf.Empty
	16, // 2: org.signal.chat.device.SetDeviceNameResponse.target_device_not_found:type_name -> org.signal.chat.errors.NotFound
	13, // 3: org.signal.chat.device.SetPushTokenRequest.apns_token_request:type_name -> org.signal.chat.device.SetPushTokenRequest.ApnsTokenRequest
	14, // 4: org.signal.chat.device.SetPushTokenRequest.fcm_token_request:type_name -> org.signal.chat.device.SetPushTokenRequest.FcmTokenRequest
	17, // 5: org.signal.chat.device.SetCapabilitiesRequest.capabilities:type_name -> org.signal.chat.common.DeviceCapability
	0,  // 6: org.signal.chat.device.Devices.GetDevices:input_type -> org.signal.chat.device.GetDevicesRequest
	2,  // 7: org.signal.chat.device.Devices.RemoveDevice:input_type -> org.signal.chat.device.RemoveDeviceRequest
	3,  // 8: org.signal.chat.device.Devices.SetDeviceName:input_type -> org.signal.chat.device.SetDeviceNameRequest
	6,  // 9: org.signal.chat.device.Devices.SetPushToken:input_type -> org.signal.chat.device.SetPushTokenRequest
	8,  // 10: org.signal.chat.device.Devices.ClearPushToken:input_type -> org.signal.chat.device.ClearPushTokenRequest
	10, // 11: org.signal.chat.device.Devices.SetCapabilities:input_type -> org.signal.chat.device.SetCapabilitiesRequest
	1,  // 12: org.signal.chat.device.Devices.GetDevices:output_type -> org.signal.chat.device.GetDevicesResponse
	5,  // 13: org.signal.chat.device.Devices.RemoveDevice:output_type -> org.signal.chat.device.RemoveDeviceResponse
	4,  // 14: org.signal.chat.device.Devices.SetDeviceName:output_type -> org.signal.chat.device.SetDeviceNameResponse
	7,  // 15: org.signal.chat.device.Devices.SetPushToken:output_type -> org.signal.chat.device.SetPushTokenResponse
	9,  // 16: org.signal.chat.device.Devices.ClearPushToken:output_type -> org.signal.chat.device.ClearPushTokenResponse
	11, // 17: org.signal.chat.device.Devices.SetCapabilities:output_type -> org.signal.chat.device.SetCapabilitiesResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_org_signal_chat_device_proto_init() }
func file_org_signal_chat_device_proto_init() {
	if File_org_signal_chat_device_proto != nil {
		return
	}
	file_org_signal_chat_device_proto_msgTypes[4].OneofWrappers = []any{
		(*SetDeviceNameResponse_Success)(nil),
		(*SetDeviceNameResponse_TargetDeviceNotFound)(nil),
	}
	file_org_signal_chat_device_proto_msgTypes[6].OneofWrappers = []any{
		(*SetPushTokenRequest_ApnsTokenRequest_)(nil),
		(*SetPushTokenRequest_FcmTokenRequest_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_signal_chat_device_proto_rawDesc), len(file_org_signal_chat_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_org_signal_chat_device_proto_goTypes,
		DependencyIndexes: file_org_signal_chat_device_proto_depIdxs,
		MessageInfos:      file_org_signal_chat_device_proto_msgTypes,
	}.Build()
	File_org_signal_chat_device_proto = out.File
	file_org_signal_chat_device_proto_goTypes = nil
	file_org_signal_chat_device_proto_depIdxs = nil
}
