//
// Copyright 2023 Signal Messenger, LLC
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: org/signal/chat/common.proto

package common

import (
	_ "go.mau.fi/mautrix-signal/pkg/signalmeow/protobuf/rpc/require"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentityType int32

const (
	IdentityType_IDENTITY_TYPE_UNSPECIFIED IdentityType = 0
	IdentityType_IDENTITY_TYPE_ACI         IdentityType = 1
	IdentityType_IDENTITY_TYPE_PNI         IdentityType = 2
)

// Enum value maps for IdentityType.
var (
	IdentityType_name = map[int32]string{
		0: "IDENTITY_TYPE_UNSPECIFIED",
		1: "IDENTITY_TYPE_ACI",
		2: "IDENTITY_TYPE_PNI",
	}
	IdentityType_value = map[string]int32{
		"IDENTITY_TYPE_UNSPECIFIED": 0,
		"IDENTITY_TYPE_ACI":         1,
		"IDENTITY_TYPE_PNI":         2,
	}
)

func (x IdentityType) Enum() *IdentityType {
	p := new(IdentityType)
	*p = x
	return p
}

func (x IdentityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentityType) Descriptor() protoreflect.EnumDescriptor {
	return file_org_signal_chat_common_proto_enumTypes[0].Descriptor()
}

func (IdentityType) Type() protoreflect.EnumType {
	return &file_org_signal_chat_common_proto_enumTypes[0]
}

func (x IdentityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdentityType.Descriptor instead.
func (IdentityType) EnumDescriptor() ([]byte, []int) {
	return file_org_signal_chat_common_proto_rawDescGZIP(), []int{0}
}

type DeviceCapability int32

const (
	DeviceCapability_DEVICE_CAPABILITY_UNSPECIFIED                  DeviceCapability = 0
	DeviceCapability_DEVICE_CAPABILITY_STORAGE                      DeviceCapability = 1
	DeviceCapability_DEVICE_CAPABILITY_TRANSFER                     DeviceCapability = 2
	DeviceCapability_DEVICE_CAPABILITY_ATTACHMENT_BACKFILL          DeviceCapability = 6
	DeviceCapability_DEVICE_CAPABILITY_SPARSE_POST_QUANTUM_RATCHET  DeviceCapability = 7
	DeviceCapability_DEVICE_CAPABILITY_PROFILES_V2                  DeviceCapability = 8
	DeviceCapability_DEVICE_CAPABILITY_USERNAME_CHANGE_SYNC_MESSAGE DeviceCapability = 9
	DeviceCapability_DEVICE_CAPABILITY_OPTIONAL_PHONE_NUMBER        DeviceCapability = 10
)

// Enum value maps for DeviceCapability.
var (
	DeviceCapability_name = map[int32]string{
		0:  "DEVICE_CAPABILITY_UNSPECIFIED",
		1:  "DEVICE_CAPABILITY_STORAGE",
		2:  "DEVICE_CAPABILITY_TRANSFER",
		6:  "DEVICE_CAPABILITY_ATTACHMENT_BACKFILL",
		7:  "DEVICE_CAPABILITY_SPARSE_POST_QUANTUM_RATCHET",
		8:  "DEVICE_CAPABILITY_PROFILES_V2",
		9:  "DEVICE_CAPABILITY_USERNAME_CHANGE_SYNC_MESSAGE",
		10: "DEVICE_CAPABILITY_OPTIONAL_PHONE_NUMBER",
	}
	DeviceCapability_value = map[string]int32{
		"DEVICE_CAPABILITY_UNSPECIFIED":                  0,
		"DEVICE_CAPABILITY_STORAGE":                      1,
		"DEVICE_CAPABILITY_TRANSFER":                     2,
		"DEVICE_CAPABILITY_ATTACHMENT_BACKFILL":          6,
		"DEVICE_CAPABILITY_SPARSE_POST_QUANTUM_RATCHET":  7,
		"DEVICE_CAPABILITY_PROFILES_V2":                  8,
		"DEVICE_CAPABILITY_USERNAME_CHANGE_SYNC_MESSAGE": 9,
		"DEVICE_CAPABILITY_OPTIONAL_PHONE_NUMBER":        10,
	}
)

func (x DeviceCapability) Enum() *DeviceCapability {
	p := new(DeviceCapability)
	*p = x
	return p
}

func (x DeviceCapability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceCapability) Descriptor() protoreflect.EnumDescriptor {
	return file_org_signal_chat_common_proto_enumTypes[1].Descriptor()
}

func (DeviceCapability) Type() protoreflect.EnumType {
	return &file_org_signal_chat_common_proto_enumTypes[1]
}

func (x DeviceCapability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceCapability.Descriptor instead.
func (DeviceCapability) EnumDescriptor() ([]byte, []int) {
	return file_org_signal_chat_common_proto_rawDescGZIP(), []int{1}
}

type ServiceIdentifier struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of identity represented by this service identifier.
	IdentityType IdentityType `protobuf:"varint,1,opt,name=identity_type,json=identityType,proto3,enum=org.signal.chat.common.IdentityType" json:"identity_type,omitempty"`
	// The UUID of the identity represented by this service identifier.
	Uuid          []byte `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceIdentifier) Reset() {
	*x = ServiceIdentifier{}
	mi := &file_org_signal_chat_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceIdentifier) ProtoMessage() {}

func (x *ServiceIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceIdentifier.ProtoReflect.Descriptor instead.
func (*ServiceIdentifier) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_common_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceIdentifier) GetIdentityType() IdentityType {
	if x != nil {
		return x.IdentityType
	}
	return IdentityType_IDENTITY_TYPE_UNSPECIFIED
}

func (x *ServiceIdentifier) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

// All identifiers associated with an account.
type AccountIdentifiers struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of service identifiers for the identified account. Always includes
	// exactly one ACI service identifier and at most one PNI service identifier.
	ServiceIdentifiers []*ServiceIdentifier `protobuf:"bytes,1,rep,name=service_identifiers,json=serviceIdentifiers,proto3" json:"service_identifiers,omitempty"`
	// The phone number associated with the identified account. May be empty if
	// the given account does not have a phone number.
	E164 string `protobuf:"bytes,2,opt,name=e164,proto3" json:"e164,omitempty"`
	// The username hash (if any) associated with the identified account. May be
	// empty if no username is associated with the identified account.
	UsernameHash []byte `protobuf:"bytes,3,opt,name=username_hash,json=usernameHash,proto3" json:"username_hash,omitempty"`
	// The username link handle UUID associated with the identified account.
	// May be empty if no username is associated with the identified account.
	UsernameLinkHandle []byte `protobuf:"bytes,4,opt,name=username_link_handle,json=usernameLinkHandle,proto3" json:"username_link_handle,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AccountIdentifiers) Reset() {
	*x = AccountIdentifiers{}
	mi := &file_org_signal_chat_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountIdentifiers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountIdentifiers) ProtoMessage() {}

func (x *AccountIdentifiers) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountIdentifiers.ProtoReflect.Descriptor instead.
func (*AccountIdentifiers) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_common_proto_rawDescGZIP(), []int{1}
}

func (x *AccountIdentifiers) GetServiceIdentifiers() []*ServiceIdentifier {
	if x != nil {
		return x.ServiceIdentifiers
	}
	return nil
}

func (x *AccountIdentifiers) GetE164() string {
	if x != nil {
		return x.E164
	}
	return ""
}

func (x *AccountIdentifiers) GetUsernameHash() []byte {
	if x != nil {
		return x.UsernameHash
	}
	return nil
}

func (x *AccountIdentifiers) GetUsernameLinkHandle() []byte {
	if x != nil {
		return x.UsernameLinkHandle
	}
	return nil
}

type EcPreKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A locally-unique identifier for this key, which will be provided by
	// peers using this key to encrypt messages so the private key can be looked
	// up.
	KeyId int32 `protobuf:"varint,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// The public key, serialized in libsignal's elliptic-curve public key format.
	PublicKey     []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EcPreKey) Reset() {
	*x = EcPreKey{}
	mi := &file_org_signal_chat_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EcPreKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EcPreKey) ProtoMessage() {}

func (x *EcPreKey) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EcPreKey.ProtoReflect.Descriptor instead.
func (*EcPreKey) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_common_proto_rawDescGZIP(), []int{2}
}

func (x *EcPreKey) GetKeyId() int32 {
	if x != nil {
		return x.KeyId
	}
	return 0
}

func (x *EcPreKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type EcSignedPreKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A locally-unique identifier for this key, which will be provided by
	// peers using this key to encrypt messages so the private key can be looked
	// up.
	KeyId int32 `protobuf:"varint,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// The public key, serialized in libsignal's elliptic-curve public key format.
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// A signature of the public key, verifiable with the identity key for the
	// account/identity associated with this pre-key.
	Signature     []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EcSignedPreKey) Reset() {
	*x = EcSignedPreKey{}
	mi := &file_org_signal_chat_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EcSignedPreKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EcSignedPreKey) ProtoMessage() {}

func (x *EcSignedPreKey) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EcSignedPreKey.ProtoReflect.Descriptor instead.
func (*EcSignedPreKey) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_common_proto_rawDescGZIP(), []int{3}
}

func (x *EcSignedPreKey) GetKeyId() int32 {
	if x != nil {
		return x.KeyId
	}
	return 0
}

func (x *EcSignedPreKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *EcSignedPreKey) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type KemSignedPreKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An locally-unique identifier for this key, which will be provided by peers
	// using this key to encrypt messages so the private key can be looked up.
	KeyId int32 `protobuf:"varint,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// The public key, serialized in libsignal's Kyber1024 public key format.
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// A signature of the public key, verifiable with the identity key for the
	// account/identity associated with this pre-key.
	Signature     []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KemSignedPreKey) Reset() {
	*x = KemSignedPreKey{}
	mi := &file_org_signal_chat_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KemSignedPreKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KemSignedPreKey) ProtoMessage() {}

func (x *KemSignedPreKey) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KemSignedPreKey.ProtoReflect.Descriptor instead.
func (*KemSignedPreKey) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_common_proto_rawDescGZIP(), []int{4}
}

func (x *KemSignedPreKey) GetKeyId() int32 {
	if x != nil {
		return x.KeyId
	}
	return 0
}

func (x *KemSignedPreKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *KemSignedPreKey) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ZkCredential struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Day on which this credential can be redeemed, in UTC seconds since epoch
	RedemptionTime int64 `protobuf:"varint,1,opt,name=redemption_time,json=redemptionTime,proto3" json:"redemption_time,omitempty"`
	// The ZK credential, using libsignal's serialization
	Credential    []byte `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZkCredential) Reset() {
	*x = ZkCredential{}
	mi := &file_org_signal_chat_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZkCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZkCredential) ProtoMessage() {}

func (x *ZkCredential) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZkCredential.ProtoReflect.Descriptor instead.
func (*ZkCredential) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_common_proto_rawDescGZIP(), []int{5}
}

func (x *ZkCredential) GetRedemptionTime() int64 {
	if x != nil {
		return x.RedemptionTime
	}
	return 0
}

func (x *ZkCredential) GetCredential() []byte {
	if x != nil {
		return x.Credential
	}
	return nil
}

// An upload location and credentials which may be used to upload an object
// to an external CDN
type UploadForm struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates the CDN type. 3 indicates resumable uploads using TUS
	Cdn uint32 `protobuf:"varint,1,opt,name=cdn,proto3" json:"cdn,omitempty"`
	// The location within the specified cdn where the finished upload can be found
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// A map of headers to include with all upload requests. Potentially contains
	// time-limited upload credentials
	Headers map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The URL to upload to with the appropriate protocol
	SignedUploadLocation string `protobuf:"bytes,4,opt,name=signed_upload_location,json=signedUploadLocation,proto3" json:"signed_upload_location,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UploadForm) Reset() {
	*x = UploadForm{}
	mi := &file_org_signal_chat_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadForm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadForm) ProtoMessage() {}

func (x *UploadForm) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadForm.ProtoReflect.Descriptor instead.
func (*UploadForm) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_common_proto_rawDescGZIP(), []int{6}
}

func (x *UploadForm) GetCdn() uint32 {
	if x != nil {
		return x.Cdn
	}
	return 0
}

func (x *UploadForm) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UploadForm) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *UploadForm) GetSignedUploadLocation() string {
	if x != nil {
		return x.SignedUploadLocation
	}
	return ""
}

// An upload location, credentials, and metadata which may be used to upload an
// object to AWS S3
type S3UploadForm struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The S3 key (i.e. path and filename) for the uploaded file.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// A scoped credential. Includes the AWS access key, date, region targeted,
	// and AWS service.
	Credential string `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	// The type of access control for the uploaded file.
	Acl string `protobuf:"bytes,3,opt,name=acl,proto3" json:"acl,omitempty"`
	// The algorithm used to calculate a signature on the S3 policy.
	Algorithm string `protobuf:"bytes,4,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	// The timestamp (formatted as "yyyyMMdd'T'HHmmssX") at which the S3 policy
	// and signature were generated.
	Date string `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	// The S3 policy (as a base64-encoded JSON string) used to upload the file.
	Policy string `protobuf:"bytes,6,opt,name=policy,proto3" json:"policy,omitempty"`
	// A digital signature (formatted as a hex string) on the S3 policy.
	Signature     string `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3UploadForm) Reset() {
	*x = S3UploadForm{}
	mi := &file_org_signal_chat_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3UploadForm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3UploadForm) ProtoMessage() {}

func (x *S3UploadForm) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3UploadForm.ProtoReflect.Descriptor instead.
func (*S3UploadForm) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_common_proto_rawDescGZIP(), []int{7}
}

func (x *S3UploadForm) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *S3UploadForm) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

func (x *S3UploadForm) GetAcl() string {
	if x != nil {
		return x.Acl
	}
	return ""
}

func (x *S3UploadForm) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *S3UploadForm) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *S3UploadForm) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *S3UploadForm) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type BadgeSvg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// File name of the scalable vector graphic for light mode.
	Light string `protobuf:"bytes,1,opt,name=light,proto3" json:"light,omitempty"`
	// File name of the scalable vector graphic for dark mode.
	Dark          string `protobuf:"bytes,2,opt,name=dark,proto3" json:"dark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BadgeSvg) Reset() {
	*x = BadgeSvg{}
	mi := &file_org_signal_chat_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BadgeSvg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BadgeSvg) ProtoMessage() {}

func (x *BadgeSvg) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BadgeSvg.ProtoReflect.Descriptor instead.
func (*BadgeSvg) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_common_proto_rawDescGZIP(), []int{8}
}

func (x *BadgeSvg) GetLight() string {
	if x != nil {
		return x.Light
	}
	return ""
}

func (x *BadgeSvg) GetDark() string {
	if x != nil {
		return x.Dark
	}
	return ""
}

type Badge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An ID that uniquely identifies the badge.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The category the badge falls in ("donor" or "other").
	Category string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	// The badge name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// The badge description.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Different size badge SVG files.
	Sprites6 []string `protobuf:"bytes,5,rep,name=sprites6,proto3" json:"sprites6,omitempty"`
	// File name of the scalable vector graphic representing this badge.
	Svg string `protobuf:"bytes,6,opt,name=svg,proto3" json:"svg,omitempty"`
	// Pairs of light/dark SVG files designed for display at different sizes.
	Svgs          []*BadgeSvg `protobuf:"bytes,7,rep,name=svgs,proto3" json:"svgs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Badge) Reset() {
	*x = Badge{}
	mi := &file_org_signal_chat_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Badge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Badge) ProtoMessage() {}

func (x *Badge) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Badge.ProtoReflect.Descriptor instead.
func (*Badge) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_common_proto_rawDescGZIP(), []int{9}
}

func (x *Badge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Badge) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Badge) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Badge) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Badge) GetSprites6() []string {
	if x != nil {
		return x.Sprites6
	}
	return nil
}

func (x *Badge) GetSvg() string {
	if x != nil {
		return x.Svg
	}
	return ""
}

func (x *Badge) GetSvgs() []*BadgeSvg {
	if x != nil {
		return x.Svgs
	}
	return nil
}

var File_org_signal_chat_common_proto protoreflect.FileDescriptor

const file_org_signal_chat_common_proto_rawDesc = "" +
	"\n" +
	"\x1corg/signal/chat/common.proto\x12\x16org.signal.chat.common\x1a\x1dorg/signal/chat/require.proto\"\x7f\n" +
	"\x11ServiceIdentifier\x12O\n" +
	"\ridentity_type\x18\x01 \x01(\x0e2$.org.signal.chat.common.IdentityTypeB\x04\x90\x97\"\x01R\fidentityType\x12\x19\n" +
	"\x04uuid\x18\x02 \x01(\fB\x05\xa2\x97\"\x01\x10R\x04uuid\"\xf1\x01\n" +
	"\x12AccountIdentifiers\x12Z\n" +
	"\x13service_identifiers\x18\x01 \x03(\v2).org.signal.chat.common.ServiceIdentifierR\x12serviceIdentifiers\x12\x18\n" +
	"\x04e164\x18\x02 \x01(\tB\x04\xa8\x97\"\x01R\x04e164\x12+\n" +
	"\rusername_hash\x18\x03 \x01(\fB\x06\xa2\x97\"\x02\x00 R\fusernameHash\x128\n" +
	"\x14username_link_handle\x18\x04 \x01(\fB\x06\xa2\x97\"\x02\x00\x10R\x12usernameLinkHandle\"N\n" +
	"\bEcPreKey\x12\x1d\n" +
	"\x06key_id\x18\x01 \x01(\x05B\x06\xb2\x97\"\x02\b\x00R\x05keyId\x12#\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fB\x04\x88\x97\"\x01R\tpublicKey\"x\n" +
	"\x0eEcSignedPreKey\x12\x1d\n" +
	"\x06key_id\x18\x01 \x01(\x05B\x06\xb2\x97\"\x02\b\x00R\x05keyId\x12#\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fB\x04\x88\x97\"\x01R\tpublicKey\x12\"\n" +
	"\tsignature\x18\x03 \x01(\fB\x04\x88\x97\"\x01R\tsignature\"y\n" +
	"\x0fKemSignedPreKey\x12\x1d\n" +
	"\x06key_id\x18\x01 \x01(\x05B\x06\xb2\x97\"\x02\b\x00R\x05keyId\x12#\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fB\x04\x88\x97\"\x01R\tpublicKey\x12\"\n" +
	"\tsignature\x18\x03 \x01(\fB\x04\x88\x97\"\x01R\tsignature\"]\n" +
	"\fZkCredential\x12'\n" +
	"\x0fredemption_time\x18\x01 \x01(\x03R\x0eredemptionTime\x12$\n" +
	"\n" +
	"credential\x18\x02 \x01(\fB\x04\x88\x97\"\x01R\n" +
	"credential\"\xed\x01\n" +
	"\n" +
	"UploadForm\x12\x10\n" +
	"\x03cdn\x18\x01 \x01(\rR\x03cdn\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12I\n" +
	"\aheaders\x18\x03 \x03(\v2/.org.signal.chat.common.UploadForm.HeadersEntryR\aheaders\x124\n" +
	"\x16signed_upload_location\x18\x04 \x01(\tR\x14signedUploadLocation\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xba\x01\n" +
	"\fS3UploadForm\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1e\n" +
	"\n" +
	"credential\x18\x02 \x01(\tR\n" +
	"credential\x12\x10\n" +
	"\x03acl\x18\x03 \x01(\tR\x03acl\x12\x1c\n" +
	"\talgorithm\x18\x04 \x01(\tR\talgorithm\x12\x12\n" +
	"\x04date\x18\x05 \x01(\tR\x04date\x12\x16\n" +
	"\x06policy\x18\x06 \x01(\tR\x06policy\x12\x1c\n" +
	"\tsignature\x18\a \x01(\tR\tsignature\"4\n" +
	"\bBadgeSvg\x12\x14\n" +
	"\x05light\x18\x01 \x01(\tR\x05light\x12\x12\n" +
	"\x04dark\x18\x02 \x01(\tR\x04dark\"\xcd\x01\n" +
	"\x05Badge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bsprites6\x18\x05 \x03(\tR\bsprites6\x12\x10\n" +
	"\x03svg\x18\x06 \x01(\tR\x03svg\x124\n" +
	"\x04svgs\x18\a \x03(\v2 .org.signal.chat.common.BadgeSvgR\x04svgs*[\n" +
	"\fIdentityType\x12\x1d\n" +
	"\x19IDENTITY_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11IDENTITY_TYPE_ACI\x10\x01\x12\x15\n" +
	"\x11IDENTITY_TYPE_PNI\x10\x02*\xe8\x02\n" +
	"\x10DeviceCapability\x12!\n" +
	"\x1dDEVICE_CAPABILITY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19DEVICE_CAPABILITY_STORAGE\x10\x01\x12\x1e\n" +
	"\x1aDEVICE_CAPABILITY_TRANSFER\x10\x02\x12)\n" +
	"%DEVICE_CAPABILITY_ATTACHMENT_BACKFILL\x10\x06\x121\n" +
	"-DEVICE_CAPABILITY_SPARSE_POST_QUANTUM_RATCHET\x10\a\x12!\n" +
	"\x1dDEVICE_CAPABILITY_PROFILES_V2\x10\b\x122\n" +
	".DEVICE_CAPABILITY_USERNAME_CHANGE_SYNC_MESSAGE\x10\t\x12+\n" +
	"'DEVICE_CAPABILITY_OPTIONAL_PHONE_NUMBER\x10\n" +
	"\"\x04\b\x03\x10\x03\"\x04\b\x04\x10\x04\"\x04\b\x05\x10\x05B\x02P\x01b\x06proto3"

var (
	file_org_signal_chat_common_proto_rawDescOnce sync.Once
	file_org_signal_chat_common_proto_rawDescData []byte
)

func file_org_signal_chat_common_proto_rawDescGZIP() []byte {
	file_org_signal_chat_common_proto_rawDescOnce.Do(func() {
		file_org_signal_chat_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_signal_chat_common_proto_rawDesc), len(file_org_signal_chat_common_proto_rawDesc)))
	})
	return file_org_signal_chat_common_proto_rawDescData
}

var file_org_signal_chat_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_org_signal_chat_common_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_org_signal_chat_common_proto_goTypes = []any{
	(IdentityType)(0),          // 0: org.signal.chat.common.IdentityType
	(DeviceCapability)(0),      // 1: org.signal.chat.common.DeviceCapability
	(*ServiceIdentifier)(nil),  // 2: org.signal.chat.common.ServiceIdentifier
	(*AccountIdentifiers)(nil), // 3: org.signal.chat.common.AccountIdentifiers
	(*EcPreKey)(nil),           // 4: org.signal.chat.common.EcPreKey
	(*EcSignedPreKey)(nil),     // 5: org.signal.chat.common.EcSignedPreKey
	(*KemSignedPreKey)(nil),    // 6: org.signal.chat.common.KemSignedPreKey
	(*ZkCredential)(nil),       // 7: org.signal.chat.common.ZkCredential
	(*UploadForm)(nil),         // 8: org.signal.chat.common.UploadForm
	(*S3UploadForm)(nil),       // 9: org.signal.chat.common.S3UploadForm
	(*BadgeSvg)(nil),           // 10: org.signal.chat.common.BadgeSvg
	(*Badge)(nil),              // 11: org.signal.chat.common.Badge
	nil,                        // 12: org.signal.chat.common.UploadForm.HeadersEntry
}
var file_org_signal_chat_common_proto_depIdxs = []int32{
	0,  // 0: org.signal.chat.common.ServiceIdentifier.identity_type:type_name -> org.signal.chat.common.IdentityType
	2,  // 1: org.signal.chat.common.AccountIdentifiers.service_identifiers:type_name -> org.signal.chat.common.ServiceIdentifier
	12, // 2: org.signal.chat.common.UploadForm.headers:type_name -> org.signal.chat.common.UploadForm.HeadersEntry
	10, // 3: org.signal.chat.common.Badge.svgs:type_name -> org.signal.chat.common.BadgeSvg
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_org_signal_chat_common_proto_init() }
func file_org_signal_chat_common_proto_init() {
	if File_org_signal_chat_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_signal_chat_common_proto_rawDesc), len(file_org_signal_chat_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_signal_chat_common_proto_goTypes,
		DependencyIndexes: file_org_signal_chat_common_proto_depIdxs,
		EnumInfos:         file_org_signal_chat_common_proto_enumTypes,
		MessageInfos:      file_org_signal_chat_common_proto_msgTypes,
	}.Build()
	File_org_signal_chat_common_proto = out.File
	file_org_signal_chat_common_proto_goTypes = nil
	file_org_signal_chat_common_proto_depIdxs = nil
}
