//
// Copyright 2023 Signal Messenger, LLC
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: org/signal/chat/require.proto

package require

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Auth int32

const (
	Auth_AUTH_UNSPECIFIED        Auth = 0
	Auth_AUTH_ONLY_AUTHENTICATED Auth = 1
	Auth_AUTH_ONLY_ANONYMOUS     Auth = 2
)

// Enum value maps for Auth.
var (
	Auth_name = map[int32]string{
		0: "AUTH_UNSPECIFIED",
		1: "AUTH_ONLY_AUTHENTICATED",
		2: "AUTH_ONLY_ANONYMOUS",
	}
	Auth_value = map[string]int32{
		"AUTH_UNSPECIFIED":        0,
		"AUTH_ONLY_AUTHENTICATED": 1,
		"AUTH_ONLY_ANONYMOUS":     2,
	}
)

func (x Auth) Enum() *Auth {
	p := new(Auth)
	*p = x
	return p
}

func (x Auth) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Auth) Descriptor() protoreflect.EnumDescriptor {
	return file_org_signal_chat_require_proto_enumTypes[0].Descriptor()
}

func (Auth) Type() protoreflect.EnumType {
	return &file_org_signal_chat_require_proto_enumTypes[0]
}

func (x Auth) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Auth.Descriptor instead.
func (Auth) EnumDescriptor() ([]byte, []int) {
	return file_org_signal_chat_require_proto_rawDescGZIP(), []int{0}
}

// This is duplicated from common.proto because:
//
// 1. importing would be a circular dependency
// 2. the canonical declaration belongs there
type IdentityType int32

const (
	IdentityType_IDENTITY_TYPE_UNSPECIFIED IdentityType = 0
	IdentityType_IDENTITY_TYPE_ACI         IdentityType = 1
	IdentityType_IDENTITY_TYPE_PNI         IdentityType = 2
)

// Enum value maps for IdentityType.
var (
	IdentityType_name = map[int32]string{
		0: "IDENTITY_TYPE_UNSPECIFIED",
		1: "IDENTITY_TYPE_ACI",
		2: "IDENTITY_TYPE_PNI",
	}
	IdentityType_value = map[string]int32{
		"IDENTITY_TYPE_UNSPECIFIED": 0,
		"IDENTITY_TYPE_ACI":         1,
		"IDENTITY_TYPE_PNI":         2,
	}
)

func (x IdentityType) Enum() *IdentityType {
	p := new(IdentityType)
	*p = x
	return p
}

func (x IdentityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentityType) Descriptor() protoreflect.EnumDescriptor {
	return file_org_signal_chat_require_proto_enumTypes[1].Descriptor()
}

func (IdentityType) Type() protoreflect.EnumType {
	return &file_org_signal_chat_require_proto_enumTypes[1]
}

func (x IdentityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdentityType.Descriptor instead.
func (IdentityType) EnumDescriptor() ([]byte, []int) {
	return file_org_signal_chat_require_proto_rawDescGZIP(), []int{1}
}

type ElementConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NonEmpty      *bool                  `protobuf:"varint,1,opt,name=nonEmpty,proto3,oneof" json:"nonEmpty,omitempty"`
	Size          *SizeConstraint        `protobuf:"bytes,2,opt,name=size,proto3,oneof" json:"size,omitempty"`
	ExactlySize   []uint32               `protobuf:"varint,3,rep,packed,name=exactlySize,proto3" json:"exactlySize,omitempty"`
	E164          *bool                  `protobuf:"varint,4,opt,name=e164,proto3,oneof" json:"e164,omitempty"`
	Base64Url     *bool                  `protobuf:"varint,5,opt,name=base64url,proto3,oneof" json:"base64url,omitempty"`
	Range         *ValueRangeConstraint  `protobuf:"bytes,6,opt,name=range,proto3,oneof" json:"range,omitempty"`
	IdentityType  *IdentityType          `protobuf:"varint,7,opt,name=identityType,proto3,enum=org.signal.chat.require.IdentityType,oneof" json:"identityType,omitempty"`
	Specified     *bool                  `protobuf:"varint,8,opt,name=specified,proto3,oneof" json:"specified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElementConstraint) Reset() {
	*x = ElementConstraint{}
	mi := &file_org_signal_chat_require_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElementConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementConstraint) ProtoMessage() {}

func (x *ElementConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_require_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementConstraint.ProtoReflect.Descriptor instead.
func (*ElementConstraint) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_require_proto_rawDescGZIP(), []int{0}
}

func (x *ElementConstraint) GetNonEmpty() bool {
	if x != nil && x.NonEmpty != nil {
		return *x.NonEmpty
	}
	return false
}

func (x *ElementConstraint) GetSize() *SizeConstraint {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *ElementConstraint) GetExactlySize() []uint32 {
	if x != nil {
		return x.ExactlySize
	}
	return nil
}

func (x *ElementConstraint) GetE164() bool {
	if x != nil && x.E164 != nil {
		return *x.E164
	}
	return false
}

func (x *ElementConstraint) GetBase64Url() bool {
	if x != nil && x.Base64Url != nil {
		return *x.Base64Url
	}
	return false
}

func (x *ElementConstraint) GetRange() *ValueRangeConstraint {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *ElementConstraint) GetIdentityType() IdentityType {
	if x != nil && x.IdentityType != nil {
		return *x.IdentityType
	}
	return IdentityType_IDENTITY_TYPE_UNSPECIFIED
}

func (x *ElementConstraint) GetSpecified() bool {
	if x != nil && x.Specified != nil {
		return *x.Specified
	}
	return false
}

type SizeConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           *uint32                `protobuf:"varint,1,opt,name=min,proto3,oneof" json:"min,omitempty"`
	Max           *uint32                `protobuf:"varint,2,opt,name=max,proto3,oneof" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SizeConstraint) Reset() {
	*x = SizeConstraint{}
	mi := &file_org_signal_chat_require_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SizeConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeConstraint) ProtoMessage() {}

func (x *SizeConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_require_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeConstraint.ProtoReflect.Descriptor instead.
func (*SizeConstraint) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_require_proto_rawDescGZIP(), []int{1}
}

func (x *SizeConstraint) GetMin() uint32 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

func (x *SizeConstraint) GetMax() uint32 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

type ValueRangeConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           *int64                 `protobuf:"varint,1,opt,name=min,proto3,oneof" json:"min,omitempty"`
	Max           *int64                 `protobuf:"varint,2,opt,name=max,proto3,oneof" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueRangeConstraint) Reset() {
	*x = ValueRangeConstraint{}
	mi := &file_org_signal_chat_require_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueRangeConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueRangeConstraint) ProtoMessage() {}

func (x *ValueRangeConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_require_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueRangeConstraint.ProtoReflect.Descriptor instead.
func (*ValueRangeConstraint) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_require_proto_rawDescGZIP(), []int{2}
}

func (x *ValueRangeConstraint) GetMin() int64 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

func (x *ValueRangeConstraint) GetMax() int64 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

var file_org_signal_chat_require_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         70001,
		Name:          "org.signal.chat.require.nonEmpty",
		Tag:           "varint,70001,opt,name=nonEmpty",
		Filename:      "org/signal/chat/require.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         70002,
		Name:          "org.signal.chat.require.specified",
		Tag:           "varint,70002,opt,name=specified",
		Filename:      "org/signal/chat/require.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*SizeConstraint)(nil),
		Field:         70003,
		Name:          "org.signal.chat.require.size",
		Tag:           "bytes,70003,opt,name=size",
		Filename:      "org/signal/chat/require.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: ([]uint32)(nil),
		Field:         70004,
		Name:          "org.signal.chat.require.exactlySize",
		Tag:           "varint,70004,rep,packed,name=exactlySize",
		Filename:      "org/signal/chat/require.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         70005,
		Name:          "org.signal.chat.require.e164",
		Tag:           "varint,70005,opt,name=e164",
		Filename:      "org/signal/chat/require.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*ValueRangeConstraint)(nil),
		Field:         70006,
		Name:          "org.signal.chat.require.range",
		Tag:           "bytes,70006,opt,name=range",
		Filename:      "org/signal/chat/require.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         70007,
		Name:          "org.signal.chat.require.present",
		Tag:           "varint,70007,opt,name=present",
		Filename:      "org/signal/chat/require.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         70008,
		Name:          "org.signal.chat.require.base64url",
		Tag:           "varint,70008,opt,name=base64url",
		Filename:      "org/signal/chat/require.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*IdentityType)(nil),
		Field:         70009,
		Name:          "org.signal.chat.require.identityType",
		Tag:           "varint,70009,opt,name=identityType,enum=org.signal.chat.require.IdentityType",
		Filename:      "org/signal/chat/require.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*ElementConstraint)(nil),
		Field:         70010,
		Name:          "org.signal.chat.require.each",
		Tag:           "bytes,70010,opt,name=each",
		Filename:      "org/signal/chat/require.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*Auth)(nil),
		Field:         71001,
		Name:          "org.signal.chat.require.auth",
		Tag:           "varint,71001,opt,name=auth,enum=org.signal.chat.require.Auth",
		Filename:      "org/signal/chat/require.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// Requires a field to have content of non-zero size/length.
	// Applies to both `optional` and regular fields, i.e. if the field is not set
	// or has a default value, it's considered to be empty. This does not apply
	// to fields that are contained in a `oneof`.
	//
	// ```
	// import "org/signal/chat/require.proto";
	//
	//	message Data {
	//	  string nonEmptyString = 1 [(require.nonEmpty) = true];
	//	  bytes nonEmptyBytes = 2 [(require.nonEmpty) = true];
	//	  optional string nonEmptyStringOptional = 3 [(require.nonEmpty) = true];
	//	  optional bytes nonEmptyBytesOptional = 4 [(require.nonEmpty) = true];
	//	  repeated string nonEmptyList = 5 [(require.nonEmpty) = true];
	//	}
	//
	// ```
	//
	// Applicable to fields of type `string`, `byte`, and `repeated` fields.
	//
	// optional bool nonEmpty = 70001;
	E_NonEmpty = &file_org_signal_chat_require_proto_extTypes[0]
	// Requires a enum field to have value with an index greater than zero.
	// Applies to both `optional` and regular fields, i.e. if the field is not set or has a default value,
	// its index will be <= 0.
	//
	// ```
	// import "org/signal/chat/require.proto";
	//
	//	message Data {
	//	  Color color = 1 [(require.specified) = true];
	//	}
	//
	//	enum Color {
	//	  COLOR_UNSPECIFIED = 0;
	//	  COLOR_RED = 1;
	//	  COLOR_GREEN = 2;
	//	  COLOR_BLUE = 3;
	//	}
	//
	// ```
	//
	// optional bool specified = 70002;
	E_Specified = &file_org_signal_chat_require_proto_extTypes[1]
	// Requires a size/length of a field to be within certain boundaries.
	// Applies to both `optional` and regular fields, i.e. if the field is not set
	// or has a default value, its size considered to be zero. However, if the
	// field is contained in a `oneof` and is not set, this annotation does not
	// apply.
	//
	// ```
	// import "org/signal/chat/require.proto";
	//
	// message Data {
	//
	//	  string name = 1 [(require.size) = {min: 3, max: 8}];
	//
	//	  optional string address = 2 [(require.size) = {min: 3, max: 8}];
	//	}
	//
	// ```
	//
	// Applicable to fields of type `string`, `byte`, and `repeated` fields.
	//
	// optional org.signal.chat.require.SizeConstraint size = 70003;
	E_Size = &file_org_signal_chat_require_proto_extTypes[2]
	// Requires a size/length of a field to be within certain boundaries.
	// Applies to both `optional` and regular fields, i.e. if the field is not set
	// or has a default value, its size considered to be zero. However, if the
	// field is contained in a `oneof` and is not set, this annotation does not
	// apply.
	//
	// ```
	// import "org/signal/chat/require.proto";
	//
	// message Data {
	//
	//	  string zip = 1 [(require.exactlySize) = 5];
	//
	//	  optional string exactlySizeVariants = 2 [(require.exactlySize) = 2, (require.exactlySize) = 4];
	//	}
	//
	// ```
	//
	// Applicable to fields of type `string`, `byte`, and `repeated` fields.
	//
	// repeated uint32 exactlySize = 70004;
	E_ExactlySize = &file_org_signal_chat_require_proto_extTypes[3]
	// Requires a value of a string field to be a valid E164-normalized phone number.
	// If the field is `optional`, this check allows a value to be not set.
	//
	//	```
	//	import "org/signal/chat/require.proto";
	//
	//	message Data {
	//	  string number = 1 [(require.e164)];
	//	}
	//	```
	//
	// optional bool e164 = 70005;
	E_E164 = &file_org_signal_chat_require_proto_extTypes[4]
	// Requires an integer value to be within a certain range. The range boundaries are specified
	// with the values of type `int32`, which should be enough for all practical purposes.
	//
	// If the field is `optional`, this check allows a value to be not set.
	//
	// ```
	// import "org/signal/chat/require.proto";
	//
	//	message Data {
	//	  int32 byte = 1 [(require.range) = {min: -128, max: 127}];
	//	  uint32 unsignedByte = 2 [(require.range).max = 255];
	//	}
	//
	// ```
	//
	// optional org.signal.chat.require.ValueRangeConstraint range = 70006;
	E_Range = &file_org_signal_chat_require_proto_extTypes[5]
	// Require a value of a message field to be present.
	//
	// Applies to both `optional` and regular fields (both of which have explicit
	// presence for the message type anyways). This does not apply to fields that
	// are contained in a `oneof`.
	//
	// ```
	// import "org/signal/chat/require.proto";
	//
	//	message Data {
	//	  message MyMessage {}
	//	  MyMessage myMessage = 1 [(require.present) = true];
	//	}
	//
	// ````
	//
	// optional bool present = 70007;
	E_Present = &file_org_signal_chat_require_proto_extTypes[6]
	// Requires a value of a string field to be a valid base64 URL string. The
	// string may be padded or unpadded. If the field is `optional`, this check
	// allows a value to be not set.
	//
	//	```
	//	import "org/signal/chat/require.proto";
	//
	//	message Data {
	//	  string myString = 1 [(require.base64url) = true];
	//	}
	//	```
	//
	// optional bool base64url = 70008;
	E_Base64Url = &file_org_signal_chat_require_proto_extTypes[7]
	// Requires a common.ServiceIdentifier field to have its IdentityType
	// be the given type (`aci` or `pni`).
	//
	//	```
	//	import "org/signal/chat/require.proto";
	//	import "org/signal/chat/common.proto";
	//
	//	message Data {
	//	  common.ServiceIdentifier accountIdentifier = 1 [(require.identityType) = IDENTITY_TYPE_ACI];
	//	}
	//	```
	//
	// optional org.signal.chat.require.IdentityType identityType = 70009;
	E_IdentityType = &file_org_signal_chat_require_proto_extTypes[8]
	// Applies element-wise constraints to the elements of a `repeated` field.
	// Top-level `require.*` annotations on a `repeated` field constrain the
	// collection itself (e.g. element count), `each` constrains the
	// individual elements.
	//
	// ```
	// import "org/signal/chat/require.proto";
	//
	//	message Data {
	//	  // 1-20 username hashes, each exactly 32 bytes
	//	  repeated bytes username_hashes = 1 [
	//	    (require.size) = {min: 1, max: 20},
	//	    (require.each) = { exactlySize: 32 }
	//	  ];
	//	}
	//
	// ```
	//
	// Applicable only to `repeated` fields.
	//
	// optional org.signal.chat.require.ElementConstraint each = 70010;
	E_Each = &file_org_signal_chat_require_proto_extTypes[9]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// Indicates that all methods in a given service require a certain kind of authentication.
	//
	// ```
	// import "org/signal/chat/require.proto";
	//
	//	service AuthService {
	//	  option (require.auth) = AUTH_ONLY_AUTHENTICATED;
	//
	//	  rpc AuthenticatedMethod (google.protobuf.Empty) returns (google.protobuf.Empty) {}
	//	}
	//
	// ```
	//
	// optional org.signal.chat.require.Auth auth = 71001;
	E_Auth = &file_org_signal_chat_require_proto_extTypes[10]
)

var File_org_signal_chat_require_proto protoreflect.FileDescriptor

const file_org_signal_chat_require_proto_rawDesc = "" +
	"\n" +
	"\x1dorg/signal/chat/require.proto\x12\x17org.signal.chat.require\x1a google/protobuf/descriptor.proto\"\xe7\x03\n" +
	"\x11ElementConstraint\x12\x1f\n" +
	"\bnonEmpty\x18\x01 \x01(\bH\x00R\bnonEmpty\x88\x01\x01\x12@\n" +
	"\x04size\x18\x02 \x01(\v2'.org.signal.chat.require.SizeConstraintH\x01R\x04size\x88\x01\x01\x12 \n" +
	"\vexactlySize\x18\x03 \x03(\rR\vexactlySize\x12\x17\n" +
	"\x04e164\x18\x04 \x01(\bH\x02R\x04e164\x88\x01\x01\x12!\n" +
	"\tbase64url\x18\x05 \x01(\bH\x03R\tbase64url\x88\x01\x01\x12H\n" +
	"\x05range\x18\x06 \x01(\v2-.org.signal.chat.require.ValueRangeConstraintH\x04R\x05range\x88\x01\x01\x12N\n" +
	"\fidentityType\x18\a \x01(\x0e2%.org.signal.chat.require.IdentityTypeH\x05R\fidentityType\x88\x01\x01\x12!\n" +
	"\tspecified\x18\b \x01(\bH\x06R\tspecified\x88\x01\x01B\v\n" +
	"\t_nonEmptyB\a\n" +
	"\x05_sizeB\a\n" +
	"\x05_e164B\f\n" +
	"\n" +
	"_base64urlB\b\n" +
	"\x06_rangeB\x0f\n" +
	"\r_identityTypeB\f\n" +
	"\n" +
	"_specified\"N\n" +
	"\x0eSizeConstraint\x12\x15\n" +
	"\x03min\x18\x01 \x01(\rH\x00R\x03min\x88\x01\x01\x12\x15\n" +
	"\x03max\x18\x02 \x01(\rH\x01R\x03max\x88\x01\x01B\x06\n" +
	"\x04_minB\x06\n" +
	"\x04_max\"T\n" +
	"\x14ValueRangeConstraint\x12\x15\n" +
	"\x03min\x18\x01 \x01(\x03H\x00R\x03min\x88\x01\x01\x12\x15\n" +
	"\x03max\x18\x02 \x01(\x03H\x01R\x03max\x88\x01\x01B\x06\n" +
	"\x04_minB\x06\n" +
	"\x04_max*R\n" +
	"\x04Auth\x12\x14\n" +
	"\x10AUTH_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17AUTH_ONLY_AUTHENTICATED\x10\x01\x12\x17\n" +
	"\x13AUTH_ONLY_ANONYMOUS\x10\x02*[\n" +
	"\fIdentityType\x12\x1d\n" +
	"\x19IDENTITY_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11IDENTITY_TYPE_ACI\x10\x01\x12\x15\n" +
	"\x11IDENTITY_TYPE_PNI\x10\x02:>\n" +
	"\bnonEmpty\x12\x1d.google.protobuf.FieldOptions\x18\xf1\xa2\x04 \x01(\bR\bnonEmpty\x88\x01\x01:@\n" +
	"\tspecified\x12\x1d.google.protobuf.FieldOptions\x18\xf2\xa2\x04 \x01(\bR\tspecified\x88\x01\x01:_\n" +
	"\x04size\x12\x1d.google.protobuf.FieldOptions\x18\xf3\xa2\x04 \x01(\v2'.org.signal.chat.require.SizeConstraintR\x04size\x88\x01\x01:A\n" +
	"\vexactlySize\x12\x1d.google.protobuf.FieldOptions\x18\xf4\xa2\x04 \x03(\rR\vexactlySize:6\n" +
	"\x04e164\x12\x1d.google.protobuf.FieldOptions\x18\xf5\xa2\x04 \x01(\bR\x04e164\x88\x01\x01:g\n" +
	"\x05range\x12\x1d.google.protobuf.FieldOptions\x18\xf6\xa2\x04 \x01(\v2-.org.signal.chat.require.ValueRangeConstraintR\x05range\x88\x01\x01:<\n" +
	"\apresent\x12\x1d.google.protobuf.FieldOptions\x18\xf7\xa2\x04 \x01(\bR\apresent\x88\x01\x01:@\n" +
	"\tbase64url\x12\x1d.google.protobuf.FieldOptions\x18\xf8\xa2\x04 \x01(\bR\tbase64url\x88\x01\x01:m\n" +
	"\fidentityType\x12\x1d.google.protobuf.FieldOptions\x18\xf9\xa2\x04 \x01(\x0e2%.org.signal.chat.require.IdentityTypeR\fidentityType\x88\x01\x01:b\n" +
	"\x04each\x12\x1d.google.protobuf.FieldOptions\x18\xfa\xa2\x04 \x01(\v2*.org.signal.chat.require.ElementConstraintR\x04each\x88\x01\x01:W\n" +
	"\x04auth\x12\x1f.google.protobuf.ServiceOptions\x18٪\x04 \x01(\x0e2\x1d.org.signal.chat.require.AuthR\x04auth\x88\x01\x01B\x02P\x01b\x06proto3"

var (
	file_org_signal_chat_require_proto_rawDescOnce sync.Once
	file_org_signal_chat_require_proto_rawDescData []byte
)

func file_org_signal_chat_require_proto_rawDescGZIP() []byte {
	file_org_signal_chat_require_proto_rawDescOnce.Do(func() {
		file_org_signal_chat_require_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_signal_chat_require_proto_rawDesc), len(file_org_signal_chat_require_proto_rawDesc)))
	})
	return file_org_signal_chat_require_proto_rawDescData
}

var file_org_signal_chat_require_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_org_signal_chat_require_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_org_signal_chat_require_proto_goTypes = []any{
	(Auth)(0),                           // 0: org.signal.chat.require.Auth
	(IdentityType)(0),                   // 1: org.signal.chat.require.IdentityType
	(*ElementConstraint)(nil),           // 2: org.signal.chat.require.ElementConstraint
	(*SizeConstraint)(nil),              // 3: org.signal.chat.require.SizeConstraint
	(*ValueRangeConstraint)(nil),        // 4: org.signal.chat.require.ValueRangeConstraint
	(*descriptorpb.FieldOptions)(nil),   // 5: google.protobuf.FieldOptions
	(*descriptorpb.ServiceOptions)(nil), // 6: google.protobuf.ServiceOptions
}
var file_org_signal_chat_require_proto_depIdxs = []int32{
	3,  // 0: org.signal.chat.require.ElementConstraint.size:type_name -> org.signal.chat.require.SizeConstraint
	4,  // 1: org.signal.chat.require.ElementConstraint.range:type_name -> org.signal.chat.require.ValueRangeConstraint
	1,  // 2: org.signal.chat.require.ElementConstraint.identityType:type_name -> org.signal.chat.require.IdentityType
	5,  // 3: org.signal.chat.require.nonEmpty:extendee -> google.protobuf.FieldOptions
	5,  // 4: org.signal.chat.require.specified:extendee -> google.protobuf.FieldOptions
	5,  // 5: org.signal.chat.require.size:extendee -> google.protobuf.FieldOptions
	5,  // 6: org.signal.chat.require.exactlySize:extendee -> google.protobuf.FieldOptions
	5,  // 7: org.signal.chat.require.e164:extendee -> google.protobuf.FieldOptions
	5,  // 8: org.signal.chat.require.range:extendee -> google.protobuf.FieldOptions
	5,  // 9: org.signal.chat.require.present:extendee -> google.protobuf.FieldOptions
	5,  // 10: org.signal.chat.require.base64url:extendee -> google.protobuf.FieldOptions
	5,  // 11: org.signal.chat.require.identityType:extendee -> google.protobuf.FieldOptions
	5,  // 12: org.signal.chat.require.each:extendee -> google.protobuf.FieldOptions
	6,  // 13: org.signal.chat.require.auth:extendee -> google.protobuf.ServiceOptions
	3,  // 14: org.signal.chat.require.size:type_name -> org.signal.chat.require.SizeConstraint
	4,  // 15: org.signal.chat.require.range:type_name -> org.signal.chat.require.ValueRangeConstraint
	1,  // 16: org.signal.chat.require.identityType:type_name -> org.signal.chat.require.IdentityType
	2,  // 17: org.signal.chat.require.each:type_name -> org.signal.chat.require.ElementConstraint
	0,  // 18: org.signal.chat.require.auth:type_name -> org.signal.chat.require.Auth
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	14, // [14:19] is the sub-list for extension type_name
	3,  // [3:14] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_org_signal_chat_require_proto_init() }
func file_org_signal_chat_require_proto_init() {
	if File_org_signal_chat_require_proto != nil {
		return
	}
	file_org_signal_chat_require_proto_msgTypes[0].OneofWrappers = []any{}
	file_org_signal_chat_require_proto_msgTypes[1].OneofWrappers = []any{}
	file_org_signal_chat_require_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_signal_chat_require_proto_rawDesc), len(file_org_signal_chat_require_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 11,
			NumServices:   0,
		},
		GoTypes:           file_org_signal_chat_require_proto_goTypes,
		DependencyIndexes: file_org_signal_chat_require_proto_depIdxs,
		EnumInfos:         file_org_signal_chat_require_proto_enumTypes,
		MessageInfos:      file_org_signal_chat_require_proto_msgTypes,
		ExtensionInfos:    file_org_signal_chat_require_proto_extTypes,
	}.Build()
	File_org_signal_chat_require_proto = out.File
	file_org_signal_chat_require_proto_goTypes = nil
	file_org_signal_chat_require_proto_depIdxs = nil
}
