default_color_bg=
default_color_fg=
dialog_attr=
dialog_attr_selected=reverse
dialog_color_bg=
dialog_color_fg=0x007063
dialog_shaded_color_bg=
dialog_shaded_color_fg=gray
entry_attr=
entry_color_bg=
entry_color_fg=
help_attr=reverse
help_color_bg=black
help_color_fg=white
history_name_attr=
history_name_attr_selected=bold
history_name_recv_color_bg=
history_name_recv_color_fg=0x8C61FF
history_name_recv_group_color_bg=
history_name_recv_group_color_fg=usercolor
history_name_sent_color_bg=
history_name_sent_color_fg=0xDB61FF
history_text_attachment_color_bg=
history_text_attachment_color_fg=blue
history_text_attr=
history_text_attr_selected=bold
history_text_quoted_color_bg=
history_text_quoted_color_fg=cyan
history_text_reaction_color_bg=
history_text_reaction_color_fg=red
history_text_recv_color_bg=
history_text_recv_color_fg=0x2B009E
history_text_recv_group_color_bg=
history_text_recv_group_color_fg=0x346B00
history_text_sent_color_bg=
history_text_sent_color_fg=magenta
list_attr=
list_attr_selected=bold
list_color_bg=
list_color_fg=
list_color_unread_bg=0xe2f8e8
list_color_unread_fg=
listborder_attr=
listborder_color_bg=
listborder_color_fg=
status_attr=
status_color_bg=0xe8e2f8
status_color_fg=
top_attr=
top_color_bg=0xe8e2f8
top_color_fg=
vim_insert_attr=
vim_insert_color_bg=0xe8e2f8
vim_insert_color_fg=black
vim_normal_attr=
vim_normal_color_bg=0xe2f8e8
vim_normal_color_fg=black
vim_visual_attr=
vim_visual_color_bg=0xFBE0F0
vim_visual_color_fg=black
