//
// Copyright 2023 Signal Messenger, LLC
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: org/signal/chat/payments.proto

package payments

import (
	_ "go.mau.fi/mautrix-signal/pkg/signalmeow/protobuf/rpc/require"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCurrencyConversionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrencyConversionsRequest) Reset() {
	*x = GetCurrencyConversionsRequest{}
	mi := &file_org_signal_chat_payments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrencyConversionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrencyConversionsRequest) ProtoMessage() {}

func (x *GetCurrencyConversionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_payments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrencyConversionsRequest.ProtoReflect.Descriptor instead.
func (*GetCurrencyConversionsRequest) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_payments_proto_rawDescGZIP(), []int{0}
}

type GetCurrencyConversionsResponse struct {
	state         protoimpl.MessageState                                     `protogen:"open.v1"`
	Timestamp     uint64                                                     `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Currencies    []*GetCurrencyConversionsResponse_CurrencyConversionEntity `protobuf:"bytes,2,rep,name=currencies,proto3" json:"currencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrencyConversionsResponse) Reset() {
	*x = GetCurrencyConversionsResponse{}
	mi := &file_org_signal_chat_payments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrencyConversionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrencyConversionsResponse) ProtoMessage() {}

func (x *GetCurrencyConversionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_payments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrencyConversionsResponse.ProtoReflect.Descriptor instead.
func (*GetCurrencyConversionsResponse) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_payments_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrencyConversionsResponse) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetCurrencyConversionsResponse) GetCurrencies() []*GetCurrencyConversionsResponse_CurrencyConversionEntity {
	if x != nil {
		return x.Currencies
	}
	return nil
}

type GetCurrencyConversionsResponse_CurrencyConversionEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          string                 `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Conversions   map[string]string      `protobuf:"bytes,2,rep,name=conversions,proto3" json:"conversions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrencyConversionsResponse_CurrencyConversionEntity) Reset() {
	*x = GetCurrencyConversionsResponse_CurrencyConversionEntity{}
	mi := &file_org_signal_chat_payments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrencyConversionsResponse_CurrencyConversionEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrencyConversionsResponse_CurrencyConversionEntity) ProtoMessage() {}

func (x *GetCurrencyConversionsResponse_CurrencyConversionEntity) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_payments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrencyConversionsResponse_CurrencyConversionEntity.ProtoReflect.Descriptor instead.
func (*GetCurrencyConversionsResponse_CurrencyConversionEntity) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_payments_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetCurrencyConversionsResponse_CurrencyConversionEntity) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *GetCurrencyConversionsResponse_CurrencyConversionEntity) GetConversions() map[string]string {
	if x != nil {
		return x.Conversions
	}
	return nil
}

var File_org_signal_chat_payments_proto protoreflect.FileDescriptor

const file_org_signal_chat_payments_proto_rawDesc = "" +
	"\n" +
	"\x1eorg/signal/chat/payments.proto\x12\x18org.signal.chat.payments\x1a\x1dorg/signal/chat/require.proto\"\x1f\n" +
	"\x1dGetCurrencyConversionsRequest\"\xa9\x03\n" +
	"\x1eGetCurrencyConversionsResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12q\n" +
	"\n" +
	"currencies\x18\x02 \x03(\v2Q.org.signal.chat.payments.GetCurrencyConversionsResponse.CurrencyConversionEntityR\n" +
	"currencies\x1a\xf5\x01\n" +
	"\x18CurrencyConversionEntity\x12\x12\n" +
	"\x04base\x18\x01 \x01(\tR\x04base\x12\x84\x01\n" +
	"\vconversions\x18\x02 \x03(\v2b.org.signal.chat.payments.GetCurrencyConversionsResponse.CurrencyConversionEntity.ConversionsEntryR\vconversions\x1a>\n" +
	"\x10ConversionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xa0\x01\n" +
	"\bPayments\x12\x8d\x01\n" +
	"\x16GetCurrencyConversions\x127.org.signal.chat.payments.GetCurrencyConversionsRequest\x1a8.org.signal.chat.payments.GetCurrencyConversionsResponse\"\x00\x1a\x04\xc8\xd5\"\x01B\x02P\x01b\x06proto3"

var (
	file_org_signal_chat_payments_proto_rawDescOnce sync.Once
	file_org_signal_chat_payments_proto_rawDescData []byte
)

func file_org_signal_chat_payments_proto_rawDescGZIP() []byte {
	file_org_signal_chat_payments_proto_rawDescOnce.Do(func() {
		file_org_signal_chat_payments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_signal_chat_payments_proto_rawDesc), len(file_org_signal_chat_payments_proto_rawDesc)))
	})
	return file_org_signal_chat_payments_proto_rawDescData
}

var file_org_signal_chat_payments_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_org_signal_chat_payments_proto_goTypes = []any{
	(*GetCurrencyConversionsRequest)(nil),                           // 0: org.signal.chat.payments.GetCurrencyConversionsRequest
	(*GetCurrencyConversionsResponse)(nil),                          // 1: org.signal.chat.payments.GetCurrencyConversionsResponse
	(*GetCurrencyConversionsResponse_CurrencyConversionEntity)(nil), // 2: org.signal.chat.payments.GetCurrencyConversionsResponse.CurrencyConversionEntity
	nil, // 3: org.signal.chat.payments.GetCurrencyConversionsResponse.CurrencyConversionEntity.ConversionsEntry
}
var file_org_signal_chat_payments_proto_depIdxs = []int32{
	2, // 0: org.signal.chat.payments.GetCurrencyConversionsResponse.currencies:type_name -> org.signal.chat.payments.GetCurrencyConversionsResponse.CurrencyConversionEntity
	3, // 1: org.signal.chat.payments.GetCurrencyConversionsResponse.CurrencyConversionEntity.conversions:type_name -> org.signal.chat.payments.GetCurrencyConversionsResponse.CurrencyConversionEntity.ConversionsEntry
	0, // 2: org.signal.chat.payments.Payments.GetCurrencyConversions:input_type -> org.signal.chat.payments.GetCurrencyConversionsRequest
	1, // 3: org.signal.chat.payments.Payments.GetCurrencyConversions:output_type -> org.signal.chat.payments.GetCurrencyConversionsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_org_signal_chat_payments_proto_init() }
func file_org_signal_chat_payments_proto_init() {
	if File_org_signal_chat_payments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_signal_chat_payments_proto_rawDesc), len(file_org_signal_chat_payments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_org_signal_chat_payments_proto_goTypes,
		DependencyIndexes: file_org_signal_chat_payments_proto_depIdxs,
		MessageInfos:      file_org_signal_chat_payments_proto_msgTypes,
	}.Build()
	File_org_signal_chat_payments_proto = out.File
	file_org_signal_chat_payments_proto_goTypes = nil
	file_org_signal_chat_payments_proto_depIdxs = nil
}
