//
// Copyright 2026 Signal Messenger, LLC
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: org/signal/chat/login_purchase.proto

package login_purchase

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoginPurchase_CreateLoginReceiptCredential_FullMethodName = "/org.signal.chat.purchase.LoginPurchase/CreateLoginReceiptCredential"
)

// LoginPurchaseClient is the client API for LoginPurchase service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for one-time purchases of logins
type LoginPurchaseClient interface {
	// Obtain a ZK receipt credential for a completed one-time login payment.
	//
	// The receipt credential can then be presented at registration
	CreateLoginReceiptCredential(ctx context.Context, in *CreateLoginReceiptCredentialRequest, opts ...grpc.CallOption) (*CreateLoginReceiptCredentialResponse, error)
}

type loginPurchaseClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginPurchaseClient(cc grpc.ClientConnInterface) LoginPurchaseClient {
	return &loginPurchaseClient{cc}
}

func (c *loginPurchaseClient) CreateLoginReceiptCredential(ctx context.Context, in *CreateLoginReceiptCredentialRequest, opts ...grpc.CallOption) (*CreateLoginReceiptCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLoginReceiptCredentialResponse)
	err := c.cc.Invoke(ctx, LoginPurchase_CreateLoginReceiptCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginPurchaseServer is the server API for LoginPurchase service.
// All implementations must embed UnimplementedLoginPurchaseServer
// for forward compatibility.
//
// Service for one-time purchases of logins
type LoginPurchaseServer interface {
	// Obtain a ZK receipt credential for a completed one-time login payment.
	//
	// The receipt credential can then be presented at registration
	CreateLoginReceiptCredential(context.Context, *CreateLoginReceiptCredentialRequest) (*CreateLoginReceiptCredentialResponse, error)
	mustEmbedUnimplementedLoginPurchaseServer()
}

// UnimplementedLoginPurchaseServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoginPurchaseServer struct{}

func (UnimplementedLoginPurchaseServer) CreateLoginReceiptCredential(context.Context, *CreateLoginReceiptCredentialRequest) (*CreateLoginReceiptCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLoginReceiptCredential not implemented")
}
func (UnimplementedLoginPurchaseServer) mustEmbedUnimplementedLoginPurchaseServer() {}
func (UnimplementedLoginPurchaseServer) testEmbeddedByValue()                       {}

// UnsafeLoginPurchaseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoginPurchaseServer will
// result in compilation errors.
type UnsafeLoginPurchaseServer interface {
	mustEmbedUnimplementedLoginPurchaseServer()
}

func RegisterLoginPurchaseServer(s grpc.ServiceRegistrar, srv LoginPurchaseServer) {
	// If the following call panics, it indicates UnimplementedLoginPurchaseServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoginPurchase_ServiceDesc, srv)
}

func _LoginPurchase_CreateLoginReceiptCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLoginReceiptCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginPurchaseServer).CreateLoginReceiptCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginPurchase_CreateLoginReceiptCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginPurchaseServer).CreateLoginReceiptCredential(ctx, req.(*CreateLoginReceiptCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoginPurchase_ServiceDesc is the grpc.ServiceDesc for LoginPurchase service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoginPurchase_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "org.signal.chat.purchase.LoginPurchase",
	HandlerType: (*LoginPurchaseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLoginReceiptCredential",
			Handler:    _LoginPurchase_CreateLoginReceiptCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "org/signal/chat/login_purchase.proto",
}
