//
// Copyright 2026 Signal Messenger, LLC
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: org/signal/chat/remote_configuration.proto

package remote_configuration

import (
	common "go.mau.fi/mautrix-signal/pkg/signalmeow/protobuf/rpc/common"
	_ "go.mau.fi/mautrix-signal/pkg/signalmeow/protobuf/rpc/require"
	_ "go.mau.fi/mautrix-signal/pkg/signalmeow/protobuf/rpc/tag"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetConfigurationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If present, the etag from a prior GetConfigurationResponse. If the
	// provided etag matches the current configuration etag, the server may elide
	// the configuration response.
	Etag          []byte `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigurationRequest) Reset() {
	*x = GetConfigurationRequest{}
	mi := &file_org_signal_chat_remote_configuration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationRequest) ProtoMessage() {}

func (x *GetConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_remote_configuration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigurationRequest.ProtoReflect.Descriptor instead.
func (*GetConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_remote_configuration_proto_rawDescGZIP(), []int{0}
}

func (x *GetConfigurationRequest) GetEtag() []byte {
	if x != nil {
		return x.Etag
	}
	return nil
}

type GetConfigurationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*GetConfigurationResponse_TaggedConfiguration
	//	*GetConfigurationResponse_EtagMatched
	Response      isGetConfigurationResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigurationResponse) Reset() {
	*x = GetConfigurationResponse{}
	mi := &file_org_signal_chat_remote_configuration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationResponse) ProtoMessage() {}

func (x *GetConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_remote_configuration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigurationResponse.ProtoReflect.Descriptor instead.
func (*GetConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_remote_configuration_proto_rawDescGZIP(), []int{1}
}

func (x *GetConfigurationResponse) GetResponse() isGetConfigurationResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetConfigurationResponse) GetTaggedConfiguration() *TaggedConfiguration {
	if x != nil {
		if x, ok := x.Response.(*GetConfigurationResponse_TaggedConfiguration); ok {
			return x.TaggedConfiguration
		}
	}
	return nil
}

func (x *GetConfigurationResponse) GetEtagMatched() bool {
	if x != nil {
		if x, ok := x.Response.(*GetConfigurationResponse_EtagMatched); ok {
			return x.EtagMatched
		}
	}
	return false
}

type isGetConfigurationResponse_Response interface {
	isGetConfigurationResponse_Response()
}

type GetConfigurationResponse_TaggedConfiguration struct {
	// The full configuration and corresponding etag.
	TaggedConfiguration *TaggedConfiguration `protobuf:"bytes,1,opt,name=tagged_configuration,json=taggedConfiguration,proto3,oneof"`
}

type GetConfigurationResponse_EtagMatched struct {
	// The etag in the request matched the current configuration etag.
	EtagMatched bool `protobuf:"varint,2,opt,name=etag_matched,json=etagMatched,proto3,oneof"`
}

func (*GetConfigurationResponse_TaggedConfiguration) isGetConfigurationResponse_Response() {}

func (*GetConfigurationResponse_EtagMatched) isGetConfigurationResponse_Response() {}

type Configuration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A map of namespaced configuration keys to their resolved values. All
	// configuration values are represented as strings. boolean values are
	// represented as the strings "true" or "false".
	Configuration map[string]string `protobuf:"bytes,1,rep,name=configuration,proto3" json:"configuration,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_org_signal_chat_remote_configuration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_remote_configuration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_remote_configuration_proto_rawDescGZIP(), []int{2}
}

func (x *Configuration) GetConfiguration() map[string]string {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type TaggedConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configuration *Configuration         `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	// An entity tag for `configuration`. This may be supplied in a
	// subsequent request to optimize bandwidth when the configuration has not
	// changed.
	Etag          []byte `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaggedConfiguration) Reset() {
	*x = TaggedConfiguration{}
	mi := &file_org_signal_chat_remote_configuration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaggedConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaggedConfiguration) ProtoMessage() {}

func (x *TaggedConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_remote_configuration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaggedConfiguration.ProtoReflect.Descriptor instead.
func (*TaggedConfiguration) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_remote_configuration_proto_rawDescGZIP(), []int{3}
}

func (x *TaggedConfiguration) GetConfiguration() *Configuration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *TaggedConfiguration) GetEtag() []byte {
	if x != nil {
		return x.Etag
	}
	return nil
}

type GetBadgesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If present, the etag from a prior GetBadgesResponse. If the provided etag
	// matches the current badge etag, the server may elide the badge response.
	Etag          []byte `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBadgesRequest) Reset() {
	*x = GetBadgesRequest{}
	mi := &file_org_signal_chat_remote_configuration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBadgesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBadgesRequest) ProtoMessage() {}

func (x *GetBadgesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_remote_configuration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBadgesRequest.ProtoReflect.Descriptor instead.
func (*GetBadgesRequest) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_remote_configuration_proto_rawDescGZIP(), []int{4}
}

func (x *GetBadgesRequest) GetEtag() []byte {
	if x != nil {
		return x.Etag
	}
	return nil
}

type GetBadgesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*GetBadgesResponse_TaggedBadges
	//	*GetBadgesResponse_EtagMatched
	Response      isGetBadgesResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBadgesResponse) Reset() {
	*x = GetBadgesResponse{}
	mi := &file_org_signal_chat_remote_configuration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBadgesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBadgesResponse) ProtoMessage() {}

func (x *GetBadgesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_remote_configuration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBadgesResponse.ProtoReflect.Descriptor instead.
func (*GetBadgesResponse) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_remote_configuration_proto_rawDescGZIP(), []int{5}
}

func (x *GetBadgesResponse) GetResponse() isGetBadgesResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetBadgesResponse) GetTaggedBadges() *TaggedBadges {
	if x != nil {
		if x, ok := x.Response.(*GetBadgesResponse_TaggedBadges); ok {
			return x.TaggedBadges
		}
	}
	return nil
}

func (x *GetBadgesResponse) GetEtagMatched() bool {
	if x != nil {
		if x, ok := x.Response.(*GetBadgesResponse_EtagMatched); ok {
			return x.EtagMatched
		}
	}
	return false
}

type isGetBadgesResponse_Response interface {
	isGetBadgesResponse_Response()
}

type GetBadgesResponse_TaggedBadges struct {
	// The full set of badges and corresponding etag.
	TaggedBadges *TaggedBadges `protobuf:"bytes,1,opt,name=tagged_badges,json=taggedBadges,proto3,oneof"`
}

type GetBadgesResponse_EtagMatched struct {
	// The etag in the request matched the current badge etag.
	EtagMatched bool `protobuf:"varint,2,opt,name=etag_matched,json=etagMatched,proto3,oneof"`
}

func (*GetBadgesResponse_TaggedBadges) isGetBadgesResponse_Response() {}

func (*GetBadgesResponse_EtagMatched) isGetBadgesResponse_Response() {}

type Badges struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A map of badge ID to the detailed information for that badge.
	Badges        map[string]*common.Badge `protobuf:"bytes,1,rep,name=badges,proto3" json:"badges,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Badges) Reset() {
	*x = Badges{}
	mi := &file_org_signal_chat_remote_configuration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Badges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Badges) ProtoMessage() {}

func (x *Badges) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_remote_configuration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Badges.ProtoReflect.Descriptor instead.
func (*Badges) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_remote_configuration_proto_rawDescGZIP(), []int{6}
}

func (x *Badges) GetBadges() map[string]*common.Badge {
	if x != nil {
		return x.Badges
	}
	return nil
}

type TaggedBadges struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Badges *Badges                `protobuf:"bytes,1,opt,name=badges,proto3" json:"badges,omitempty"`
	// An entity tag for `badges`. This may be supplied in a subsequent request
	// to optimize bandwidth when the set of badges has not changed.
	Etag          []byte `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaggedBadges) Reset() {
	*x = TaggedBadges{}
	mi := &file_org_signal_chat_remote_configuration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaggedBadges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaggedBadges) ProtoMessage() {}

func (x *TaggedBadges) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_remote_configuration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaggedBadges.ProtoReflect.Descriptor instead.
func (*TaggedBadges) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_remote_configuration_proto_rawDescGZIP(), []int{7}
}

func (x *TaggedBadges) GetBadges() *Badges {
	if x != nil {
		return x.Badges
	}
	return nil
}

func (x *TaggedBadges) GetEtag() []byte {
	if x != nil {
		return x.Etag
	}
	return nil
}

var File_org_signal_chat_remote_configuration_proto protoreflect.FileDescriptor

const file_org_signal_chat_remote_configuration_proto_rawDesc = "" +
	"\n" +
	"*org/signal/chat/remote_configuration.proto\x12#org.signal.chat.remoteconfiguration\x1a\x1corg/signal/chat/common.proto\x1a\x1dorg/signal/chat/require.proto\x1a\x19org/signal/chat/tag.proto\"-\n" +
	"\x17GetConfigurationRequest\x12\x12\n" +
	"\x04etag\x18\x01 \x01(\fR\x04etag\"\xca\x01\n" +
	"\x18GetConfigurationResponse\x12m\n" +
	"\x14tagged_configuration\x18\x01 \x01(\v28.org.signal.chat.remoteconfiguration.TaggedConfigurationH\x00R\x13taggedConfiguration\x123\n" +
	"\fetag_matched\x18\x02 \x01(\bB\x0e\xc2\xd5\"\n" +
	"etag_matchH\x00R\vetagMatchedB\n" +
	"\n" +
	"\bresponse\"\xbe\x01\n" +
	"\rConfiguration\x12k\n" +
	"\rconfiguration\x18\x01 \x03(\v2E.org.signal.chat.remoteconfiguration.Configuration.ConfigurationEntryR\rconfiguration\x1a@\n" +
	"\x12ConfigurationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x01\n" +
	"\x13TaggedConfiguration\x12X\n" +
	"\rconfiguration\x18\x01 \x01(\v22.org.signal.chat.remoteconfiguration.ConfigurationR\rconfiguration\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\fR\x04etag\"&\n" +
	"\x10GetBadgesRequest\x12\x12\n" +
	"\x04etag\x18\x01 \x01(\fR\x04etag\"\xae\x01\n" +
	"\x11GetBadgesResponse\x12X\n" +
	"\rtagged_badges\x18\x01 \x01(\v21.org.signal.chat.remoteconfiguration.TaggedBadgesH\x00R\ftaggedBadges\x123\n" +
	"\fetag_matched\x18\x02 \x01(\bB\x0e\xc2\xd5\"\n" +
	"etag_matchH\x00R\vetagMatchedB\n" +
	"\n" +
	"\bresponse\"\xb3\x01\n" +
	"\x06Badges\x12O\n" +
	"\x06badges\x18\x01 \x03(\v27.org.signal.chat.remoteconfiguration.Badges.BadgesEntryR\x06badges\x1aX\n" +
	"\vBadgesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.org.signal.chat.common.BadgeR\x05value:\x028\x01\"g\n" +
	"\fTaggedBadges\x12C\n" +
	"\x06badges\x18\x01 \x01(\v2+.org.signal.chat.remoteconfiguration.BadgesR\x06badges\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\fR\x04etag2\xad\x02\n" +
	"\x13RemoteConfiguration\x12\x91\x01\n" +
	"\x10GetConfiguration\x12<.org.signal.chat.remoteconfiguration.GetConfigurationRequest\x1a=.org.signal.chat.remoteconfiguration.GetConfigurationResponse\"\x00\x12|\n" +
	"\tGetBadges\x125.org.signal.chat.remoteconfiguration.GetBadgesRequest\x1a6.org.signal.chat.remoteconfiguration.GetBadgesResponse\"\x00\x1a\x04\xc8\xd5\"\x01B\x02P\x01b\x06proto3"

var (
	file_org_signal_chat_remote_configuration_proto_rawDescOnce sync.Once
	file_org_signal_chat_remote_configuration_proto_rawDescData []byte
)

func file_org_signal_chat_remote_configuration_proto_rawDescGZIP() []byte {
	file_org_signal_chat_remote_configuration_proto_rawDescOnce.Do(func() {
		file_org_signal_chat_remote_configuration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_signal_chat_remote_configuration_proto_rawDesc), len(file_org_signal_chat_remote_configuration_proto_rawDesc)))
	})
	return file_org_signal_chat_remote_configuration_proto_rawDescData
}

var file_org_signal_chat_remote_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_org_signal_chat_remote_configuration_proto_goTypes = []any{
	(*GetConfigurationRequest)(nil),  // 0: org.signal.chat.remoteconfiguration.GetConfigurationRequest
	(*GetConfigurationResponse)(nil), // 1: org.signal.chat.remoteconfiguration.GetConfigurationResponse
	(*Configuration)(nil),            // 2: org.signal.chat.remoteconfiguration.Configuration
	(*TaggedConfiguration)(nil),      // 3: org.signal.chat.remoteconfiguration.TaggedConfiguration
	(*GetBadgesRequest)(nil),         // 4: org.signal.chat.remoteconfiguration.GetBadgesRequest
	(*GetBadgesResponse)(nil),        // 5: org.signal.chat.remoteconfiguration.GetBadgesResponse
	(*Badges)(nil),                   // 6: org.signal.chat.remoteconfiguration.Badges
	(*TaggedBadges)(nil),             // 7: org.signal.chat.remoteconfiguration.TaggedBadges
	nil,                              // 8: org.signal.chat.remoteconfiguration.Configuration.ConfigurationEntry
	nil,                              // 9: org.signal.chat.remoteconfiguration.Badges.BadgesEntry
	(*common.Badge)(nil),             // 10: org.signal.chat.common.Badge
}
var file_org_signal_chat_remote_configuration_proto_depIdxs = []int32{
	3,  // 0: org.signal.chat.remoteconfiguration.GetConfigurationResponse.tagged_configuration:type_name -> org.signal.chat.remoteconfiguration.TaggedConfiguration
	8,  // 1: org.signal.chat.remoteconfiguration.Configuration.configuration:type_name -> org.signal.chat.remoteconfiguration.Configuration.ConfigurationEntry
	2,  // 2: org.signal.chat.remoteconfiguration.TaggedConfiguration.configuration:type_name -> org.signal.chat.remoteconfiguration.Configuration
	7,  // 3: org.signal.chat.remoteconfiguration.GetBadgesResponse.tagged_badges:type_name -> org.signal.chat.remoteconfiguration.TaggedBadges
	9,  // 4: org.signal.chat.remoteconfiguration.Badges.badges:type_name -> org.signal.chat.remoteconfiguration.Badges.BadgesEntry
	6,  // 5: org.signal.chat.remoteconfiguration.TaggedBadges.badges:type_name -> org.signal.chat.remoteconfiguration.Badges
	10, // 6: org.signal.chat.remoteconfiguration.Badges.BadgesEntry.value:type_name -> org.signal.chat.common.Badge
	0,  // 7: org.signal.chat.remoteconfiguration.RemoteConfiguration.GetConfiguration:input_type -> org.signal.chat.remoteconfiguration.GetConfigurationRequest
	4,  // 8: org.signal.chat.remoteconfiguration.RemoteConfiguration.GetBadges:input_type -> org.signal.chat.remoteconfiguration.GetBadgesRequest
	1,  // 9: org.signal.chat.remoteconfiguration.RemoteConfiguration.GetConfiguration:output_type -> org.signal.chat.remoteconfiguration.GetConfigurationResponse
	5,  // 10: org.signal.chat.remoteconfiguration.RemoteConfiguration.GetBadges:output_type -> org.signal.chat.remoteconfiguration.GetBadgesResponse
	9,  // [9:11] is the sub-list for method output_type
	7,  // [7:9] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_org_signal_chat_remote_configuration_proto_init() }
func file_org_signal_chat_remote_configuration_proto_init() {
	if File_org_signal_chat_remote_configuration_proto != nil {
		return
	}
	file_org_signal_chat_remote_configuration_proto_msgTypes[1].OneofWrappers = []any{
		(*GetConfigurationResponse_TaggedConfiguration)(nil),
		(*GetConfigurationResponse_EtagMatched)(nil),
	}
	file_org_signal_chat_remote_configuration_proto_msgTypes[5].OneofWrappers = []any{
		(*GetBadgesResponse_TaggedBadges)(nil),
		(*GetBadgesResponse_EtagMatched)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_signal_chat_remote_configuration_proto_rawDesc), len(file_org_signal_chat_remote_configuration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_org_signal_chat_remote_configuration_proto_goTypes,
		DependencyIndexes: file_org_signal_chat_remote_configuration_proto_depIdxs,
		MessageInfos:      file_org_signal_chat_remote_configuration_proto_msgTypes,
	}.Build()
	File_org_signal_chat_remote_configuration_proto = out.File
	file_org_signal_chat_remote_configuration_proto_goTypes = nil
	file_org_signal_chat_remote_configuration_proto_depIdxs = nil
}
