//
// Copyright 2026 Signal Messenger, LLC
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: org/signal/chat/remote_configuration.proto

package remote_configuration

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RemoteConfiguration_GetConfiguration_FullMethodName = "/org.signal.chat.remoteconfiguration.RemoteConfiguration/GetConfiguration"
	RemoteConfiguration_GetBadges_FullMethodName        = "/org.signal.chat.remoteconfiguration.RemoteConfiguration/GetBadges"
)

// RemoteConfigurationClient is the client API for RemoteConfiguration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Provides remote configuration applicable to the authenticated user
type RemoteConfigurationClient interface {
	// Fetches the configuration for the authenticated user. Returned
	// values are based on the authenticated account and caller's client platform,
	// which is derived from the "User-Agent" header.
	GetConfiguration(ctx context.Context, in *GetConfigurationRequest, opts ...grpc.CallOption) (*GetConfigurationResponse, error)
	// Returns detailed information for all configured badges, keyed by badge ID.
	//
	// Badge descriptions may contain localized strings. Callers should set their
	// language preferences via an "Accept-Language" header on the request
	// https://datatracker.ietf.org/doc/html/rfc3282#section-3
	//
	// Callers may cache a badges result for up to 1 day before checking (via
	// etag) if there are any new updates.
	GetBadges(ctx context.Context, in *GetBadgesRequest, opts ...grpc.CallOption) (*GetBadgesResponse, error)
}

type remoteConfigurationClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoteConfigurationClient(cc grpc.ClientConnInterface) RemoteConfigurationClient {
	return &remoteConfigurationClient{cc}
}

func (c *remoteConfigurationClient) GetConfiguration(ctx context.Context, in *GetConfigurationRequest, opts ...grpc.CallOption) (*GetConfigurationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigurationResponse)
	err := c.cc.Invoke(ctx, RemoteConfiguration_GetConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteConfigurationClient) GetBadges(ctx context.Context, in *GetBadgesRequest, opts ...grpc.CallOption) (*GetBadgesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBadgesResponse)
	err := c.cc.Invoke(ctx, RemoteConfiguration_GetBadges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteConfigurationServer is the server API for RemoteConfiguration service.
// All implementations must embed UnimplementedRemoteConfigurationServer
// for forward compatibility.
//
// Provides remote configuration applicable to the authenticated user
type RemoteConfigurationServer interface {
	// Fetches the configuration for the authenticated user. Returned
	// values are based on the authenticated account and caller's client platform,
	// which is derived from the "User-Agent" header.
	GetConfiguration(context.Context, *GetConfigurationRequest) (*GetConfigurationResponse, error)
	// Returns detailed information for all configured badges, keyed by badge ID.
	//
	// Badge descriptions may contain localized strings. Callers should set their
	// language preferences via an "Accept-Language" header on the request
	// https://datatracker.ietf.org/doc/html/rfc3282#section-3
	//
	// Callers may cache a badges result for up to 1 day before checking (via
	// etag) if there are any new updates.
	GetBadges(context.Context, *GetBadgesRequest) (*GetBadgesResponse, error)
	mustEmbedUnimplementedRemoteConfigurationServer()
}

// UnimplementedRemoteConfigurationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemoteConfigurationServer struct{}

func (UnimplementedRemoteConfigurationServer) GetConfiguration(context.Context, *GetConfigurationRequest) (*GetConfigurationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfiguration not implemented")
}
func (UnimplementedRemoteConfigurationServer) GetBadges(context.Context, *GetBadgesRequest) (*GetBadgesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBadges not implemented")
}
func (UnimplementedRemoteConfigurationServer) mustEmbedUnimplementedRemoteConfigurationServer() {}
func (UnimplementedRemoteConfigurationServer) testEmbeddedByValue()                             {}

// UnsafeRemoteConfigurationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemoteConfigurationServer will
// result in compilation errors.
type UnsafeRemoteConfigurationServer interface {
	mustEmbedUnimplementedRemoteConfigurationServer()
}

func RegisterRemoteConfigurationServer(s grpc.ServiceRegistrar, srv RemoteConfigurationServer) {
	// If the following call panics, it indicates UnimplementedRemoteConfigurationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RemoteConfiguration_ServiceDesc, srv)
}

func _RemoteConfiguration_GetConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteConfigurationServer).GetConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteConfiguration_GetConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteConfigurationServer).GetConfiguration(ctx, req.(*GetConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteConfiguration_GetBadges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBadgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteConfigurationServer).GetBadges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteConfiguration_GetBadges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteConfigurationServer).GetBadges(ctx, req.(*GetBadgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RemoteConfiguration_ServiceDesc is the grpc.ServiceDesc for RemoteConfiguration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemoteConfiguration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "org.signal.chat.remoteconfiguration.RemoteConfiguration",
	HandlerType: (*RemoteConfigurationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfiguration",
			Handler:    _RemoteConfiguration_GetConfiguration_Handler,
		},
		{
			MethodName: "GetBadges",
			Handler:    _RemoteConfiguration_GetBadges_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "org/signal/chat/remote_configuration.proto",
}
