//
// Copyright 2026 Signal Messenger, LLC
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: org/signal/chat/challenge.proto

package challenge

import (
	_ "go.mau.fi/mautrix-signal/pkg/signalmeow/protobuf/rpc/require"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnswerChallengeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The opaque token id from the ChallengeRequired response returned by the
	// server endpoint that requested the challenge
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Types that are valid to be assigned to Request:
	//
	//	*AnswerChallengeRequest_Push
	//	*AnswerChallengeRequest_Captcha
	Request       isAnswerChallengeRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerChallengeRequest) Reset() {
	*x = AnswerChallengeRequest{}
	mi := &file_org_signal_chat_challenge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerChallengeRequest) ProtoMessage() {}

func (x *AnswerChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_challenge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerChallengeRequest.ProtoReflect.Descriptor instead.
func (*AnswerChallengeRequest) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_challenge_proto_rawDescGZIP(), []int{0}
}

func (x *AnswerChallengeRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AnswerChallengeRequest) GetRequest() isAnswerChallengeRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AnswerChallengeRequest) GetPush() *AnswerChallengeRequest_AnswerPushChallengeRequest {
	if x != nil {
		if x, ok := x.Request.(*AnswerChallengeRequest_Push); ok {
			return x.Push
		}
	}
	return nil
}

func (x *AnswerChallengeRequest) GetCaptcha() *AnswerChallengeRequest_AnswerCaptchaChallengeRequest {
	if x != nil {
		if x, ok := x.Request.(*AnswerChallengeRequest_Captcha); ok {
			return x.Captcha
		}
	}
	return nil
}

type isAnswerChallengeRequest_Request interface {
	isAnswerChallengeRequest_Request()
}

type AnswerChallengeRequest_Push struct {
	Push *AnswerChallengeRequest_AnswerPushChallengeRequest `protobuf:"bytes,2,opt,name=push,proto3,oneof"`
}

type AnswerChallengeRequest_Captcha struct {
	Captcha *AnswerChallengeRequest_AnswerCaptchaChallengeRequest `protobuf:"bytes,3,opt,name=captcha,proto3,oneof"`
}

func (*AnswerChallengeRequest_Push) isAnswerChallengeRequest_Request() {}

func (*AnswerChallengeRequest_Captcha) isAnswerChallengeRequest_Request() {}

type AnswerChallengeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the challenge proof was accepted
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerChallengeResponse) Reset() {
	*x = AnswerChallengeResponse{}
	mi := &file_org_signal_chat_challenge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerChallengeResponse) ProtoMessage() {}

func (x *AnswerChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_challenge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerChallengeResponse.ProtoReflect.Descriptor instead.
func (*AnswerChallengeResponse) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_challenge_proto_rawDescGZIP(), []int{1}
}

func (x *AnswerChallengeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AnswerChallengeRequest_AnswerPushChallengeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The challenge string provided to the client via a push payload
	Challenge     string `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerChallengeRequest_AnswerPushChallengeRequest) Reset() {
	*x = AnswerChallengeRequest_AnswerPushChallengeRequest{}
	mi := &file_org_signal_chat_challenge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerChallengeRequest_AnswerPushChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerChallengeRequest_AnswerPushChallengeRequest) ProtoMessage() {}

func (x *AnswerChallengeRequest_AnswerPushChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_challenge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerChallengeRequest_AnswerPushChallengeRequest.ProtoReflect.Descriptor instead.
func (*AnswerChallengeRequest_AnswerPushChallengeRequest) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_challenge_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AnswerChallengeRequest_AnswerPushChallengeRequest) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

type AnswerChallengeRequest_AnswerCaptchaChallengeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A string representing a solved captcha
	// Example: signal-hcaptcha.30b01b46-d8c9-4c30-bbd7-9719acfe0c10.challenge.abcdefg1345
	Captcha       string `protobuf:"bytes,1,opt,name=captcha,proto3" json:"captcha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerChallengeRequest_AnswerCaptchaChallengeRequest) Reset() {
	*x = AnswerChallengeRequest_AnswerCaptchaChallengeRequest{}
	mi := &file_org_signal_chat_challenge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerChallengeRequest_AnswerCaptchaChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerChallengeRequest_AnswerCaptchaChallengeRequest) ProtoMessage() {}

func (x *AnswerChallengeRequest_AnswerCaptchaChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_challenge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerChallengeRequest_AnswerCaptchaChallengeRequest.ProtoReflect.Descriptor instead.
func (*AnswerChallengeRequest_AnswerCaptchaChallengeRequest) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_challenge_proto_rawDescGZIP(), []int{0, 1}
}

func (x *AnswerChallengeRequest_AnswerCaptchaChallengeRequest) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

var File_org_signal_chat_challenge_proto protoreflect.FileDescriptor

const file_org_signal_chat_challenge_proto_rawDesc = "" +
	"\n" +
	"\x1forg/signal/chat/challenge.proto\x12\x19org.signal.chat.challenge\x1a\x1dorg/signal/chat/require.proto\"\x93\x03\n" +
	"\x16AnswerChallengeRequest\x12\x1a\n" +
	"\x05token\x18\x01 \x01(\tB\x04\x88\x97\"\x01R\x05token\x12b\n" +
	"\x04push\x18\x02 \x01(\v2L.org.signal.chat.challenge.AnswerChallengeRequest.AnswerPushChallengeRequestH\x00R\x04push\x12k\n" +
	"\acaptcha\x18\x03 \x01(\v2O.org.signal.chat.challenge.AnswerChallengeRequest.AnswerCaptchaChallengeRequestH\x00R\acaptcha\x1a@\n" +
	"\x1aAnswerPushChallengeRequest\x12\"\n" +
	"\tchallenge\x18\x01 \x01(\tB\x04\x88\x97\"\x01R\tchallenge\x1a?\n" +
	"\x1dAnswerCaptchaChallengeRequest\x12\x1e\n" +
	"\acaptcha\x18\x01 \x01(\tB\x04\x88\x97\"\x01R\acaptchaB\t\n" +
	"\arequest\"3\n" +
	"\x17AnswerChallengeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x96\x01\n" +
	"\tChallenge\x12\x82\x01\n" +
	"\x17HandleChallengeResponse\x121.org.signal.chat.challenge.AnswerChallengeRequest\x1a2.org.signal.chat.challenge.AnswerChallengeResponse\"\x00\x1a\x04\xc8\xd5\"\x01B\x02P\x01b\x06proto3"

var (
	file_org_signal_chat_challenge_proto_rawDescOnce sync.Once
	file_org_signal_chat_challenge_proto_rawDescData []byte
)

func file_org_signal_chat_challenge_proto_rawDescGZIP() []byte {
	file_org_signal_chat_challenge_proto_rawDescOnce.Do(func() {
		file_org_signal_chat_challenge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_signal_chat_challenge_proto_rawDesc), len(file_org_signal_chat_challenge_proto_rawDesc)))
	})
	return file_org_signal_chat_challenge_proto_rawDescData
}

var file_org_signal_chat_challenge_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_org_signal_chat_challenge_proto_goTypes = []any{
	(*AnswerChallengeRequest)(nil),                               // 0: org.signal.chat.challenge.AnswerChallengeRequest
	(*AnswerChallengeResponse)(nil),                              // 1: org.signal.chat.challenge.AnswerChallengeResponse
	(*AnswerChallengeRequest_AnswerPushChallengeRequest)(nil),    // 2: org.signal.chat.challenge.AnswerChallengeRequest.AnswerPushChallengeRequest
	(*AnswerChallengeRequest_AnswerCaptchaChallengeRequest)(nil), // 3: org.signal.chat.challenge.AnswerChallengeRequest.AnswerCaptchaChallengeRequest
}
var file_org_signal_chat_challenge_proto_depIdxs = []int32{
	2, // 0: org.signal.chat.challenge.AnswerChallengeRequest.push:type_name -> org.signal.chat.challenge.AnswerChallengeRequest.AnswerPushChallengeRequest
	3, // 1: org.signal.chat.challenge.AnswerChallengeRequest.captcha:type_name -> org.signal.chat.challenge.AnswerChallengeRequest.AnswerCaptchaChallengeRequest
	0, // 2: org.signal.chat.challenge.Challenge.HandleChallengeResponse:input_type -> org.signal.chat.challenge.AnswerChallengeRequest
	1, // 3: org.signal.chat.challenge.Challenge.HandleChallengeResponse:output_type -> org.signal.chat.challenge.AnswerChallengeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_org_signal_chat_challenge_proto_init() }
func file_org_signal_chat_challenge_proto_init() {
	if File_org_signal_chat_challenge_proto != nil {
		return
	}
	file_org_signal_chat_challenge_proto_msgTypes[0].OneofWrappers = []any{
		(*AnswerChallengeRequest_Push)(nil),
		(*AnswerChallengeRequest_Captcha)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_signal_chat_challenge_proto_rawDesc), len(file_org_signal_chat_challenge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_org_signal_chat_challenge_proto_goTypes,
		DependencyIndexes: file_org_signal_chat_challenge_proto_depIdxs,
		MessageInfos:      file_org_signal_chat_challenge_proto_msgTypes,
	}.Build()
	File_org_signal_chat_challenge_proto = out.File
	file_org_signal_chat_challenge_proto_goTypes = nil
	file_org_signal_chat_challenge_proto_depIdxs = nil
}
