#!/usr/bin/env bash
#
# assemble.sh
#
# Copyright (c) 2026 Kristofer Berggren
# All rights reserved.
#
# nchat is distributed under the MIT license, see LICENSE for details.
#
# Build the combined WhatsApp+Signal Go c-archive (libgostat).
#
# A static (non-shared) nchat links the protocol c-archives directly into the
# executable. Two independent Go c-archives cannot co-link — each embeds its own
# Go runtime and its own copy of mattn/go-sqlite3's cgo export trampolines, which
# collide at the final link. This script sidesteps that by assembling ONE module
# that hosts both protocols as separate Go packages (so their ~identically-named
# top-level identifiers never clash) and building a single c-archive with one
# embedded runtime.
#
# The two protocol source dirs (lib/wmchat/go, lib/sgchat/go) are NOT modified:
# their .go files are copied into per-protocol subpackages here, the ONLY
# transformation being the package clause (package main -> package wmchat/signal).
# The heavy vendored dependency trees (ext/whatsmeow, ext/signal) are referenced
# in place via go.mod replace directives, not copied.
#
# Usage:
#   assemble.sh WM_DIR SG_DIR STAGE_DIR OUT_DIR LIB BUILDMODE [go build flags...]
#
# Environment (set by the caller / CMake):
#   GOPATH, LIBRARY_PATH (libsignal_ffi dir), CGO_ENABLED=1

set -euo pipefail

WM_DIR="$1"      # source dir lib/wmchat/go
SG_DIR="$2"      # source dir lib/sgchat/go
STAGE="$3"       # staging module dir (build tree)
OUT="$4"         # output dir for the archive + generated headers
LIB="$5"         # archive filename, e.g. libgostat.a
BUILDMODE="$6"   # c-archive (static) or c-shared
shift 6
GOFLAGS_EXTRA=("$@")

MODULE=github.com/d99kris/nchat/lib/gostat

# --- (re)assemble the combined module from the two untouched protocol dirs ---
rm -rf "$STAGE"
mkdir -p "$STAGE/wmchat" "$STAGE/signal" "$OUT"

sed 's/^package main$/package wmchat/' "$WM_DIR/gowm.go"  > "$STAGE/wmchat/gowm.go"
sed 's/^package main$/package wmchat/' "$WM_DIR/cgowm.go" > "$STAGE/wmchat/cgowm.go"
sed 's/^package main$/package signal/' "$SG_DIR/gosg.go"  > "$STAGE/signal/gosg.go"
sed 's/^package main$/package signal/' "$SG_DIR/cgosg.go" > "$STAGE/signal/cgosg.go"

# Single empty main() that imports both subpackages so their //export symbols
# are pulled into the archive.
cat > "$STAGE/main.go" <<EOF
// Generated by lib/gostat/assemble.sh — do not edit.
package main

import (
	_ "$MODULE/signal"
	_ "$MODULE/wmchat"
)

func main() {}
EOF

# Seed go.mod with only the two replace directives; -mod=mod derives the full
# (unioned) dependency graph from the two vendored modules automatically, so
# this needs no hand-maintained require list that could drift on a dep bump.
cat > "$STAGE/go.mod" <<EOF
module $MODULE

go 1.25.0

replace go.mau.fi/whatsmeow => $WM_DIR/ext/whatsmeow
replace go.mau.fi/mautrix-signal => $SG_DIR/ext/signal
EOF

# Union of the two go.sum files (both pin identical shared-dep versions, so a
# plain dedup is safe); -mod=mod fills any remaining entries.
cat "$WM_DIR/go.sum" "$SG_DIR/go.sum" | sort -u > "$STAGE/go.sum"

# --- build the single combined c-archive ---
cd "$STAGE"
go build -mod=mod -buildmode="$BUILDMODE" "${GOFLAGS_EXTRA[@]}" -o "$OUT/$LIB" .

# --- generate the per-protocol cgo export headers (CWm*/CSg* prototypes) ---
# go build only emits a header for the main package (empty here), so harvest each
# subpackage's export header directly. These match the standalone builds'
# libcgowm.h / libcgosg.h, which the C++ (wmchat.cpp / sgchat.cpp) #include.
#
# `go tool cgo -objdir DIR` is inconsistent about DIR: the generated sources land
# inside it (DIR/_cgo_export.h), but the intermediate type-probe objects use it as
# a filename prefix and land beside it (DIR + _cgo_N.o -> .hdr/wm_cgo_2.o), whose
# parent must already exist. Pre-create the objdirs so both writes succeed;
# without this the probe compile fails with "unable to open output file ... .o".
rm -rf "$STAGE/.hdr"
mkdir -p "$STAGE/.hdr/wm" "$STAGE/.hdr/sg"
( cd "$STAGE/wmchat" && go tool cgo -objdir "$STAGE/.hdr/wm" -- cgowm.go )
cp "$STAGE/.hdr/wm/_cgo_export.h" "$OUT/libcgowm.h"
( cd "$STAGE/signal" && go tool cgo -objdir "$STAGE/.hdr/sg" -- cgosg.go )
cp "$STAGE/.hdr/sg/_cgo_export.h" "$OUT/libcgosg.h"
