//
// Copyright 2025 Signal Messenger, LLC
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: org/signal/chat/errors.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Response message that indicates a particular resource was not found.
type NotFound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotFound) Reset() {
	*x = NotFound{}
	mi := &file_org_signal_chat_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotFound) ProtoMessage() {}

func (x *NotFound) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotFound.ProtoReflect.Descriptor instead.
func (*NotFound) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_errors_proto_rawDescGZIP(), []int{0}
}

// Response message that indicates that some precondition of the request was not
// met. For example, if there was a request to update foo, but foo had not been
// set, this would be an appropriate error.
type FailedPrecondition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An optional description indicating what precondition failed.
	Description   string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailedPrecondition) Reset() {
	*x = FailedPrecondition{}
	mi := &file_org_signal_chat_errors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailedPrecondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailedPrecondition) ProtoMessage() {}

func (x *FailedPrecondition) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_errors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailedPrecondition.ProtoReflect.Descriptor instead.
func (*FailedPrecondition) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_errors_proto_rawDescGZIP(), []int{1}
}

func (x *FailedPrecondition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Response message that authentication via an anonymous credential failed.
type FailedZkAuthentication struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An optional description with additional information about the failure.
	Description   string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailedZkAuthentication) Reset() {
	*x = FailedZkAuthentication{}
	mi := &file_org_signal_chat_errors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailedZkAuthentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailedZkAuthentication) ProtoMessage() {}

func (x *FailedZkAuthentication) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_errors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailedZkAuthentication.ProtoReflect.Descriptor instead.
func (*FailedZkAuthentication) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_errors_proto_rawDescGZIP(), []int{2}
}

func (x *FailedZkAuthentication) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Response message that indicates authorization to perform an unidentified
// operation via an endorsement or access key failed
type FailedUnidentifiedAuthorization struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An optional description with additional information about the failure.
	Description   string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailedUnidentifiedAuthorization) Reset() {
	*x = FailedUnidentifiedAuthorization{}
	mi := &file_org_signal_chat_errors_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailedUnidentifiedAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailedUnidentifiedAuthorization) ProtoMessage() {}

func (x *FailedUnidentifiedAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_errors_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailedUnidentifiedAuthorization.ProtoReflect.Descriptor instead.
func (*FailedUnidentifiedAuthorization) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_errors_proto_rawDescGZIP(), []int{3}
}

func (x *FailedUnidentifiedAuthorization) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_org_signal_chat_errors_proto protoreflect.FileDescriptor

const file_org_signal_chat_errors_proto_rawDesc = "" +
	"\n" +
	"\x1corg/signal/chat/errors.proto\x12\x16org.signal.chat.errors\"\n" +
	"\n" +
	"\bNotFound\"6\n" +
	"\x12FailedPrecondition\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\":\n" +
	"\x16FailedZkAuthentication\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\"C\n" +
	"\x1fFailedUnidentifiedAuthorization\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescriptionB\x02P\x01b\x06proto3"

var (
	file_org_signal_chat_errors_proto_rawDescOnce sync.Once
	file_org_signal_chat_errors_proto_rawDescData []byte
)

func file_org_signal_chat_errors_proto_rawDescGZIP() []byte {
	file_org_signal_chat_errors_proto_rawDescOnce.Do(func() {
		file_org_signal_chat_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_signal_chat_errors_proto_rawDesc), len(file_org_signal_chat_errors_proto_rawDesc)))
	})
	return file_org_signal_chat_errors_proto_rawDescData
}

var file_org_signal_chat_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_org_signal_chat_errors_proto_goTypes = []any{
	(*NotFound)(nil),                        // 0: org.signal.chat.errors.NotFound
	(*FailedPrecondition)(nil),              // 1: org.signal.chat.errors.FailedPrecondition
	(*FailedZkAuthentication)(nil),          // 2: org.signal.chat.errors.FailedZkAuthentication
	(*FailedUnidentifiedAuthorization)(nil), // 3: org.signal.chat.errors.FailedUnidentifiedAuthorization
}
var file_org_signal_chat_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_org_signal_chat_errors_proto_init() }
func file_org_signal_chat_errors_proto_init() {
	if File_org_signal_chat_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_signal_chat_errors_proto_rawDesc), len(file_org_signal_chat_errors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_signal_chat_errors_proto_goTypes,
		DependencyIndexes: file_org_signal_chat_errors_proto_depIdxs,
		MessageInfos:      file_org_signal_chat_errors_proto_msgTypes,
	}.Build()
	File_org_signal_chat_errors_proto = out.File
	file_org_signal_chat_errors_proto_goTypes = nil
	file_org_signal_chat_errors_proto_depIdxs = nil
}
