#!/bin/bash
docker run --rm -itv $(pwd):/data rust:1-alpine /data/update-ffi-docker-inner.sh

echo "// Generated by update-ffi.sh; DO NOT EDIT." > version.go
echo >> version.go
echo "package libsignalgo" >> version.go
echo >> version.go
cd libsignal
echo "const Version = \"$(git describe --tags --always)\"" >> ../version.go
