#!/bin/bash
docker run --rm -itv $(pwd):/data rust:1-alpine /data/update-ffi-docker-inner.sh

echo "// Generated by update-ffi.sh; DO NOT EDIT." > signalversion/version.go
echo >> signalversion/version.go
echo "package signalversion" >> signalversion/version.go
echo >> signalversion/version.go
cd libsignal
echo "const Version = \"$(git describe --tags --always)\"" >> ../signalversion/version.go
